### ISSUE TITLE
Cmd+Click on back/forward buttons should open/fork in new tab

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1011]

**Comment by victorporof** [comment]
Depends on https://github.com/electron/electron/issues/7186 or tracking history ourselves as described in https://github.com/mozilla/tofino/issues/996#issuecomment-246672736

**Comment by victorporof** [comment]
Unasigning for now.

**Comment by victorporof** [comment]
Found out about https://github.com/mozilla/tofino/pull/1120#issuecomment-246906935
