### ISSUE TITLE
Should have loading indicator when navigating

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1030]
Right now, we have no feedback when a back/forward button is clicked, or navigating for any other reason (hotkey, swiping, redirect) and feels that sometimes the action didn't go through, and then the page starts loading. I think this is partially a performance issue, but also we need some sort of feedback to let the user know something's happen. I click the navigation buttons too many times.

**Comment by victorporof** [comment]
I fixed this in the new frontend
