### ISSUE TITLE
Support for middle mouse button clicking on the tab

### ISSUE THREAD

**Issue by locosoft1986** [mozilla/tofino#106]
I feel it is a common feature when user clicks middle mouse button on the tab, the tab should be closed.
And i'm happy to open up a PR.

**Comment by AAorris** [comment]
Warming up to react I gave this a shot before noticing your existing pull request. Sorry about that!
I may throw my changes into the ring anyways.

**Comment by victorporof** [comment]
I'll wait for @phlsa's feedback before reviewing this.

**Comment by locosoft1986** [comment]
Wow, great :)
