### ISSUE TITLE
Remove browser-blueprint

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1070]
Should remove once all features are ported over to browser-modern.

Only things I can think about are the recently added gestures and page errors.

**Comment by jsantell** [comment]
Gestures re-enabled in #1071

**Comment by jsantell** [comment]
Ticket for cert errors #1072

**Comment by victorporof** [comment]
Need to fix https://github.com/mozilla/tofino/issues/347

**Comment by victorporof** [comment]
Need to fix https://github.com/mozilla/tofino/issues/348

**Comment by victorporof** [comment]
Need to fix https://github.com/mozilla/tofino/issues/349

**Comment by victorporof** [comment]
Need to also fix https://github.com/mozilla/tofino/issues/1138
