### ISSUE TITLE
Make sure the `ignored` and `temporary` lists in test-dependencies.js are always up to date

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1078]
There used to be one but I think @Mossop deleted it when switching to the two package.json structure. Since then a few packages were orphaned; we're installing them but not using them anywhere.

**Comment by Mossop** [comment]
The test I replaced it with was meant to be checking for orphaned packages too. I'll look into what's going wrong with that.

**Comment by victorporof** [comment]
Actually, I was mistaken, sorry! That test does indeed make sure packages aren't orphaned.

The issue that confused me lay in potentially having garbage accumulate in the `ignored` or `temporary` lists for those tests. Maybe it'd be a good idea to make sure everything in those lists actually exists in a package.json.

Updating this issue accordingly.
