### ISSUE TITLE
Ability to make Tofino the default browser

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1095]

**Comment by jsantell** [comment]
Electron doesn't give us anything like this, and this looks like we'll need platform specific settings for each. Few other npm modules that do similar, but all just call the browser's flags to let them do the setting, so makes sense for us to expose an arg to do similar:
https://github.com/gokulkrishh/set-default-browser/blob/master/index.js

**Comment by jsantell** [comment]
Actually, in Firefox, we just set protocol handlers https://dxr.mozilla.org/mozilla-central/source/browser/components/shell/nsMacShellService.cpp#64

Electron has similar for Windows/OSX atleast:
http://electron.atom.io/docs/all/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows
