### ISSUE TITLE
Distribute application as an installer

### ISSUE THREAD

**Issue by havenchyk** [mozilla/tofino#112]
Hey, thanks for your initiative, it's really nice to see new project based on electron.

I guess the next step will be to distribute the app, so, what do you think about [electron-builder](https://github.com/electron-userland/electron-builder)? It's a complete solution that ready to create installers for different platforms (win, osx, even linux). electron-packager is used inside as well, so you don't need to use so low-level tool.

I'll be glad to hear any feedback from core team.

**Comment by rnewman** [comment]
Quick update: we'll certainly need to do this at some point, but not just yet, which explains the lack of discussion on this issue.

**Comment by Mossop** [comment]
Right now we're using electron-packager for builds but I think I'm going to switch us to electron-builder.
