### ISSUE TITLE
History page background looks weird with no background colour

### ISSUE THREAD

**Issue by Mossop** [mozilla/tofino#1131]
Running a local development build shows the blueprint background on the history start page but on packaged builds it is just a white background.

**Comment by jsantell** [comment]
I think it's intentional to just show white background, as it's not using the blueprint theme at all anymore.

**Comment by Mossop** [comment]
Then we shouldn't be showing it when running from a development tree either. it looks pretty weird without it though.

**Comment by Mossop** [comment]
I guess I should have clobbered, it is indeed white locally too. I think it still needs something though.

**Comment by victorporof** [comment]
Dupe of https://github.com/mozilla/tofino/issues/722

**Comment by victorporof** [comment]
Didn't end up fixing things in #722, filed https://github.com/mozilla/tofino/issues/1170
