### ISSUE TITLE
Back/forward buttons become disabled when they shouldn't

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#1135]
STR:

Open a new tab
Open http://www.npr.org/
Click on a link on that page
Press back
Notice the back and forward buttons are now disabled
Click on a link again
Back and forward buttons are still disabled

Note that cmd/ctrl arrow *does* navigate properly, so it seems like this is a frontend issue

**Comment by victorporof** [comment]
I think we're not updating the canGoBack and canGoForward page state frequently enough. I'll look into it.

**Comment by victorporof** [comment]
Note that keyboard back/forward navigation isn't possible at all after https://github.com/mozilla/tofino/pull/1111 but the problem described in my previous comment still stands.
