### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by Equinox** [mozilla/tofino#1173]
In the [contributing](https://github.com/mozilla/tofino/blob/master/README.md#contributing) section of the readme, the first source link i.e: [this one](https://pfraze.github.io/2015/09/08/building-electron-browser-pt1.html), no longer exists.

The page is still out there, though: [here.](https://github.com/pfrazee/pfrazee.github.io/blob/moreaboutp2p/_posts/2015-09-08-building-electron-browser-pt1.md)

**Comment by jsantell** [comment]
Good eye and thanks for filing the issue! I'll fix this shortly.
