### ISSUE TITLE
Opening New Tab No Longer Focuses Address Bar

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#1177]
I believe this is a regression.

**Comment by bgrins** [comment]
Yes, it's a regression.  Maybe from #1164

**Comment by victorporof** [comment]
@bgrins it's not from #1164. 

https://github.com/mozilla/tofino/pull/1107 regressed selection, and https://github.com/mozilla/tofino/pull/1122 removed focusing because of a bad rebase.
