### ISSUE TITLE
Fix Overview Page's metadata parsing

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1179]
Some point this stopped working, maybe in one of the big changes recently. Turning sourcemaps to use 'eval' mode in #1178 may break fathom-web used, but we can use different sourcemap style for preload in that case (or none at all) to still get good, authored source in almost all cases.

**Comment by victorporof** [comment]
https://github.com/mozilla/tofino/commit/921311eba8c57a8550e3d6fcd0b9fe2670fbc9f8

**Comment by jsantell** [comment]
Rolling back pmp to 0.3.0, new exposed func signature for getMetadata has changed and no docs for it, and no reason to upgrade atm afaik
