### ISSUE TITLE
Nightly builds don't work on linux

### ISSUE THREAD

**Issue by ochameau** [mozilla/tofino#1248]
On linux, zip files don't preserve file permissions and you can't successfully launch tofino. (I imagine that's the same for Mac?)

On windows, tofino is completely black. UI "works" as I'm able to close the browser by clicking blindly on the close button on the upper right, but everything is black.

**Comment by victorporof** [comment]
Is the problem with the packaged builds or is everything working on when building yourself from source?

**Comment by ochameau** [comment]
Haven't tried building it from sources.
For linux, it is only a packaging issue.
It is harder to say for the issue on Windows...

**Comment by victorporof** [comment]
Packaged builds work for me on OS X

**Comment by Mossop** [comment]
Let's use this issue to track the linux issue, we probably need to switch to tar.bz2 packaging. For windows please file a new issue if you can reproduce it, it seems to work for me.
