### ISSUE TITLE
Clicking on links in pinned tabs should always open in new tab

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1263]

**Comment by jsantell** [comment]
Nice way to handle this? [No webview events](http://electron.atom.io/docs/all/#instance-events) that seem to be helpful here, and should be smart about specific types of navigation (hash change, window.location.href change should not open in new tab). Preload onClick handler could work, but might interfere with content, so that seems scary. Possibly might have to deal with an electron patch.

**Comment by Mossop** [comment]
Looks like the `will-navigate` event is probably what you want to watch for.

**Comment by jsantell** [comment]
Not sure that will work:

[will-navigate](http://electron.atom.io/docs/all/#event-will-navigate):
> It is also not emitted for in-page navigations, such as clicking anchor links or updating the window.location.hash. Use did-navigate-in-page event for this purpose.

Also, if I pin facebook, if this is implemented, does that mean anything I click on on my profile page for example opens in a new tab? I see the point of this for some cases, but I don't think it applies to every case when a user pins a tab.

**Comment by jsantell** [comment]
We could be smart about it and only open in new tab if the href's domain is different than the pinned tab, but ultimately I think will result in an unintuitive experience.

**Comment by Mossop** [comment]
Yes, only opening a new tab when the domain is different is how we should do this, just like in Firefox. I rely on that behaviour a lot. So in-page navigations shouldn't open new tabs.

**Comment by Mossop** [comment]
Looks like `will-navigate` doesn't give you a way to cancel the navigation though so I don't know if there is a way to do this in stock electron :(

**Comment by Mossop** [comment]
I filed an electron issue to see if we can get a way to cancel the navigations we don't want: https://github.com/electron/electron/issues/7501
