### ISSUE TITLE
Empty results in the location autocompletions list

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1264]
![screen shot 2016-09-28 at 10 23 04 am](https://cloud.githubusercontent.com/assets/248899/18905902/91d555b6-8565-11e6-8727-50dcfe88b746.png)

![screen shot 2016-09-28 at 10 23 29 am](https://cloud.githubusercontent.com/assets/248899/18905913/9b33b684-8565-11e6-8f24-694d20075112.png)

I started noticing this happening after https://github.com/mozilla/tofino/pull/834

@ncalexan ?

**Comment by ncalexan** [comment]
I think you already figured this all out, but what's happening is that the UAS is returning a `{ title: "", url: <URL> }` pair and there's a uri/url name mismatch, so it's not being shown at all.
