### ISSUE TITLE
Don't show page contents/transcripts in the history page

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#1273]
<img width="1100" alt="oddentry" src="https://cloud.githubusercontent.com/assets/46655/18922537/a9f27102-856e-11e6-8740-17ef23c32720.png">

It's the intro to this: https://davidwalsh.name/3d-panorama-image , not the `<title>`

**Comment by victorporof** [comment]
That's a saved page transcript. Happens when you click on the app menu and chose "Fetch page contents".

**Comment by jsantell** [comment]
We're not currently displaying page summaries.
