### ISSUE TITLE
Autocomplete selection is broken

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#1274]
When pressing `[ENTER]` or clicking on any autocomplete URL item, nothing happens.  The URL is also no longer displaying next to the title.

<img width="1089" alt="brokenautocomplete" src="https://cloud.githubusercontent.com/assets/46655/18922794/b91e29ea-856f-11e6-9ea4-874c0cfc6c9f.png">

Likely a regression.

**Comment by victorporof** [comment]
Fixed by https://github.com/mozilla/tofino/pull/1265, regressed by #834

Duping to https://github.com/mozilla/tofino/issues/1264
