### ISSUE TITLE
Amazon looks terrible in Tofino

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1304]
This used to work properly before.

![screen shot 2016-09-30 at 6 46 49 pm](https://cloud.githubusercontent.com/assets/248899/18999510/48542b58-873e-11e6-94a4-c22b2b6747f2.png)

**Comment by ncalexan** [comment]
This looks like a stylesheet failed to load.

**Comment by Mossop** [comment]
This is https://github.com/electron/electron/issues/7221 and is fixed upstream. I'll get us updated.
