### ISSUE TITLE
Frequent "user-agent-http-client.js POST http://localhost:9090/v1/sessions/start 500 (Internal Server Error)" when rapidly opening new tabs

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1321]

**Comment by ncalexan** [comment]
@victorporof do you see any logging around this?  This is a helpful spur to get the UAS logging boned up.

**Comment by ncalexan** [comment]
A little logging later, I see
```
caught error { Error: SQLITE_ERROR: cannot start a transaction within a transaction
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }
POST /v1/sessions/start 500 20.640 ms - 106
```
I thought we would block transactions at this point, but that's not so -- we need to process them sequentially.  I'll figure out what the JS version of the talking stick is.

**Comment by ncalexan** [comment]
Should be fixed by https://github.com/mozilla/tofino/commit/c905c10883c0724bd5e55bd81bfdbec46a2c5536.  Don't know why this didn't autoclose; guess my commit message syntax wasn't correct?
