### ISSUE TITLE
Consider using `withMutations` in reducers

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#135]
...so that we don't create a million temporary clones of our state while modifying it.

**Comment by jsantell** [comment]
What're the downsides here?

**Comment by victorporof** [comment]
No downsides. I don't understand how there could even be any downsides:

**Comment by victorporof** [comment]
I can work on this if there's no takers.

**Comment by linclark** [comment]
I'd be up for taking it if you haven't already started.

**Comment by victorporof** [comment]
Already started 🔨
