### ISSUE TITLE
First run of tofino on windows shows the windows firewall prompt. Again.

### ISSUE THREAD

**Issue by Mossop** [mozilla/tofino#1382]
Filed upstream but wanted to track it in our triage.

https://github.com/mozilla/datomish-user-agent-service/issues/5

**Comment by ncalexan** [comment]
Should be fixed by https://github.com/mozilla/tofino/commit/c905c10883c0724bd5e55bd81bfdbec46a2c5536.  Don't know why this didn't autoclose; guess my commit message syntax wasn't correct?
