### ISSUE TITLE
Location does not update after navigation

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1387]
Both in production and dev builds, I've ran into an issue where the location bar's URL doesn't update after navigating and doesn't start updating unless I focus and enter a new URL. I get messages in the console:

```
Skipped setting `value` on the urlbar because: user-is-typing.
```

Unsure yet of what causes this state.

**Comment by victorporof** [comment]
Are you sure those console messages are related to the location bar that you wish updated? It might be useful to log this specifically. 

Furthermore, the user-is-typing attribute should disappear after a short duration after you've stopped typing (or did anything with the keyboard while the location bar was focused, like pressing Cmd+T)

**Comment by victorporof** [comment]
Some STRs would be very useful.

**Comment by jsantell** [comment]
Yes, the messages are definitely related to this bug, and just looked at the delay, which is 500ms -- which definitely wasn't doing anything as it was 30 seconds or so.

**Comment by victorporof** [comment]
That's why I'm a bit skeptical as to those messages being directly related. The 'user-is-typing' local component state is always removed after 500ms after is being set, so I'm not sure. But again, STRs would help.

**Comment by Mossop** [comment]
That isn't entirely true, the state is removed 500ms after a keyup if the urlbar has focus while the state is set by a keydown. I wonder if there is a case where the urlbar can lose focus after the keydown but before the keyup.

**Comment by victorporof** [comment]
@Mossop That's a good point, I haven't thought of that.

**Comment by bgrins** [comment]
STR:

Open https://duckduckgo.com/?q=test
Put cursor at end of URL and hold the 'a' key
Click away from the URL bar (somewhere in the page) before releasing the key
Click on a search result
The URL bar doesn't get updated

**Comment by jsantell** [comment]
Great STR, Brian. Got a patch for this with those easy steps.
