### ISSUE TITLE
Many things broken in FiveThirtyEight 

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1405]
The "we're forecasting the election with three models" radio buttons don't work, and a handful of graphs on the page don't work. @joewalker pointed this out, and thought it might be a flash issue, but this works on Firefox with flash disabled, so not sure what's up

http://projects.fivethirtyeight.com/2016-election-forecast/

**Comment by darkwing** [comment]
Additionally, there's about 12.9% too much red on the map.  Please fix that as well.

**Comment by jsantell** [comment]
Looks like a user agent string issue. Blah.

Our webviews have the UA string (on my machine):
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.113 Electron/1.4.2 Safari/537.36`

Using my Chrome Canary UA string in webviews fixes the issue:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2878.0 Safari/537.36`
