### ISSUE TITLE
Fix issues preventing dev version from conflicting with production build

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1418]
When running a production build, intended to be a fulltime browser, there are issues when also developing Tofino. Some off the top of my head:

* Running tests opens new tabs in production build
* Running dev version when production build is running sometimes(?) doesn't start the UA service

**Comment by jsantell** [comment]
#1385

**Comment by ncalexan** [comment]
> Running dev version when production build is running sometimes(?) doesn't start the UA service

I very much expect this is just about port overlapping.  What might happen (should happen?) is that we observe an *existing* UAS and connect to it, thereby blurring the lines yet further.  I've filed https://github.com/mozilla/tofino/issues/1419 to talk about a possible solution.
