### ISSUE TITLE
Consider having main process provide UAS with Node.js server directly

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#1419]
Node.js has the ability to provide a socket or server to a child process via an IPC channel.  We might care to use this ability to start the UAS from Tofino.

The big win is that the Tofino main process can arrange to start a server and bind it to any port/interface it cares to, independently of the UAS process that services requests.  That means we don't have to much around with port-scanning in the UAS process, nor do we have to find a way to message the port back to the main process.

The big cost is that the UAS is now heavily dependent on a Node.js-specific piece of functionality.

We might achieve something similar by providing the UAS process an extra open FD when it starts, specifically for it to message its port back to the main process.  This is more general than using Node.js's implementation.

**Comment by rnewman** [comment]
This is one possible solution to communicating ports and avoiding the need for port discovery. We'll need that for our first public release.

We talked about this in triage, and we weren't comfortable tying the UAS to node so closely, so we'll close this for the moment. We'll reopen if this is the approach we take.
