### ISSUE TITLE
Autocompletions stopped working after updating UAS to 0.0.3

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1425]
500 internal server errors.

**Comment by victorporof** [comment]
Can't back down to 0.0.2 since https://github.com/mozilla/tofino/issues/1321 would prevent session restore from working properly.

**Comment by victorporof** [comment]
@ncalexan ping

**Comment by jsantell** [comment]
Fixed by incrementing datomish-user-agent-service to 0.0.4 via 6e190dca04b34439ea2b4e7aa992861efbd7a78c
