### ISSUE TITLE
Filtering in the history page stopped working after updating UAS to 0.0.3

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1442]

**Comment by victorporof** [comment]
@ncalexan ping

**Comment by rnewman** [comment]
I haven't looked at the root cause, but coincidentally I'm about to rework this in https://github.com/mozilla/datomish-user-agent-service/pull/22.

**Comment by jsantell** [comment]
Fixed by incrementing datomish-user-agent-service to 0.0.4 via 6e190dca04b34439ea2b4e7aa992861efbd7a78c
