### ISSUE TITLE
Tab gets stuck permanently on loading

### ISSUE THREAD

**Issue by joewalker** [mozilla/tofino#1490]
It's been loading for days. Across restarts even. I can't close it, un-pin it, reload it.
I eventually got rid of it by typing a new URL.
No STR right now, except that the URL on which it broke was a large google sheet, so some loading problems could be expected.

**Comment by jsantell** [comment]
Guessing this may have been from a session restore -- try nuking your session.json or use the latest tofino (@victorporof fixed yesterday)

**Comment by joewalker** [comment]
If there's a chance that we've fixed this, then lets close it, and re-open if it happens again.
