### ISSUE TITLE
Session restore stores ghost tabs

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1505]
Somehow during session restore, I have 1 tab open before closing, and when restarting, I see a bunch of other tabs that no longer exist, and I only have one open. And there's lots of redux spam setting all this up. Not sure how I got to this state yet, but definitely slows this down.

<img width="362" alt="screen shot 2016-11-01 at 12 56 04 pm" src="https://cloud.githubusercontent.com/assets/641267/19905118/9c32c4de-a032-11e6-9f26-0680cd9cf61f.png">

**Comment by jsantell** [comment]
This also creates content divs/webviews for each of these, which is probably the real source of slow down.

**Comment by jsantell** [comment]
I would note that this is beyond a UX bug, this grinds performance to the ground as handfuls of ghost webviews are created when restarting in dev environment and just one visible tab is open (luckily have not run into this in production).

**Comment by jsantell** [comment]
(nuking the session.json fixes this however)

**Comment by joewalker** [comment]
> I would note that this is beyond a UX bug

That's true. The new label that I'm proposing in place of the milestone takes out the 'UI' part.

**Comment by jsantell** [comment]
Closing, will reopen if see it again.
