### ISSUE TITLE
Should handle when there's no internet connection

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#152]
Browser gets into a broken state when there's no internets. 

Fun story: I've spent the past half an hour being confused by not knowing what was wrong with my code and how I managed to get everything to stop working. Turned out I was offline.

**Comment by jsantell** [comment]
#28 should give us this API atleast

**Comment by jsantell** [comment]
The NetError pages implemented currently handle this. If we'd like in the future, we can make a custom page for ERR_INTERNET_DISCONNECTED (-106)
