### ISSUE TITLE
Backspace on web content should navigate Back

### ISSUE THREAD

**Issue by rnewman** [mozilla/tofino#1522]
Firefox parity.

**Comment by bgrins** [comment]
Counterpoint: chrome has removed backspace for navigation, opting for cmd/ctrl+left.  This is nice once you get used to it since you don't accidentally navigate backwards when pressing backspace if an input field becomes blurred

**Comment by rnewman** [comment]
I'd also be happy for this to be WONTFIXed — it just ought to be a deliberate decision rather than omission.

**Comment by joewalker** [comment]
3 close-it votes (if you include me) and it doesn't look like rnewman is strongly for it.
I say deliberate decision made. WONTFIX.
