### ISSUE TITLE
Google search box isn't autofocused

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#1550]
STR:
Open a new tab
Type google.com and press enter

Expected:
Page loads, search box is focused

Actual:
Page loads, nothing appears to be focused

**Comment by jsantell** [comment]
I think this would be fixed if we automatically give web content focus after navigating. Reloading a google.com page focuses the search bar as expected

**Comment by jsantell** [comment]
* Reloading with web contents focused that is
