### ISSUE TITLE
Typing in the URL bar fast causes jank

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#1556]
<img width="512" alt="screen shot 2016-11-15 at 9 53 23 am" src="https://cloud.githubusercontent.com/assets/641267/20317068/67a78924-ab19-11e6-8b5d-7617397f557f.png">

**Comment by jsantell** [comment]
Looks like we synchronously handle stuff on every keydown

**Comment by rnewman** [comment]
Judging by the console output, typing involves a ton of work!

**Comment by jsantell** [comment]
Not an issue in production builds, I think. Might be a lot of React's validations in dev builds, is my guess.

**Comment by victorporof** [comment]
Console logging maybe?

**Comment by victorporof** [comment]
No jank in release.
