### ISSUE TITLE
Tofino fails to start

### ISSUE THREAD

**Issue by joewalker** [mozilla/tofino#1572]
It looks like the UA service decides to quit before we really get going:

`main ERROR: UA Service exited with exit code 201`.

Several errors, but it looks like they're all from the front-end failing to get in contact.

**Comment by rnewman** [comment]
Which platform?

Reproducible?

Is there a log?

**Comment by rnewman** [comment]
Backed out in 909ead1fb1bd571723078333e65159c187dc729d. Thanks for the report! Don't know how the tests or my previous runs missed this…

Root cause is filed as https://github.com/mozilla/datomish-user-agent-service/issues/29.
