### ISSUE TITLE
Some https sites fail cert check

### ISSUE THREAD

**Issue by joewalker** [mozilla/tofino#1574]
E.g. https://www.amazon.co.uk and https://amazon.co.uk and others

![screen shot 2016-12-01 at 06 06 58](https://cloud.githubusercontent.com/assets/76258/20783518/72733aae-b78c-11e6-9ad4-282d22618714.png)

Google is fine.

**Comment by joewalker** [comment]
Digging a bit, it also happens here: https://choosemyreward.chase.com/

So this could have something to do with https://sslmate.com/blog/post/ct_redaction_in_chrome_53

Although I'm surprised to see that this is happening to Amazon too, although Amazon does use Symantec.

**Comment by bgrins** [comment]
Updating to the latest electron (https://github.com/mozilla/tofino/pull/1571) seems to fix it

**Comment by bgrins** [comment]
@joewalker can you confirm this is fixed on latest master?

**Comment by joewalker** [comment]
Yup. Fixed. Thanks
