### ISSUE TITLE
The bookmarks star is incorrect on reddit.com

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#158]
Right now, the star flashes disabled, then enabled, then returns to disabled.  (This is either bookmarked or not; disabled is a distinct state.)

Technically, we're waiting for `did-stop-loading`.  That's wrong, but `did-finish-loading` is equally wrong.  Neither event allows us to distinguish the main frame from sub-frames.

The PR associated to https://github.com/electron/electron/issues/5183 will address this \o/

**Comment by rnewman** [comment]
This works for me in current `master`. Close?

**Comment by victorporof** [comment]
What's the status here? @ncalexan

**Comment by bgrins** [comment]
I still see flickering when bookmarking the page and then reloading

**Comment by ncalexan** [comment]
On Thu, May 19, 2016 at 3:40 PM, Brian Grinstead <notifications@github.com>
wrote:

> I still see flickering when bookmarking the page and then reloading
>
I believe this is because we have not (yet) correctly handled load events
from subframes.  That is, each subframe event mixes with the main frame
event stream, changing the page loading state and causing flicker.
Redirects factor in but should work once the subframe events are filtered
out.

**Comment by victorporof** [comment]
This should be fixed now.
