### ISSUE TITLE
Cmd+alt+r to reload the browser doesn't work again

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#164]

**Comment by victorporof** [comment]
Actually none of the menu entries are present anymore. Commit 9a6d7f1 seems to be the culprit, which is https://github.com/mozilla/tofino/commit/9a6d7f1827d397b26d3bf0dd10a93716a7301bed (couldn't find the PR anymore). @ncalexan ping.

**Comment by ncalexan** [comment]
This is on me.  I'll address this today.
