### ISSUE TITLE
Fail tests on proptype warnings

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#171]
I'm seeing  a couple of warnings locally - we should fail tests if this happens:

warning.js:45 Warning: Failed propType: Required prop `onDragStart` was not specified in `Tab`. Check the render method of `StatelessComponent`.
warning.js:45 Warning: Failed propType: Required prop `onDragEnd` was not specified in `Tab`. Check the render method of `StatelessComponent`.
warning.js:45 Warning: Failed propType: Required prop `onDragEnter` was not specified in `Tab`. Check the render method of `StatelessComponent`.
warning.js:45 Warning: Failed propType: Required prop `onDrop` was not specified in `Tab`. Check the render method of `StatelessComponent`.

**Comment by linclark** [comment]
I think this is a dupe of #35

**Comment by bgrins** [comment]
Good catch, thanks
