### ISSUE TITLE
Allow to load a single browser window from a remote URL

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#174]
This tracks making it easy to run test UI hosted on a remote URL.  This could go in a lot of directions, but I'd like to be able to navigate to a known page with a list of git branches hosted on github, and then click each link to open a new window with UI served from each git branch.  That would make it very easy to test PRs and run field tests in the wild.  (Much easier than packaging complete test browsers, which gets unwieldy.)

Technically, there are some challenges.  WebView pre-load scripts must be served from secure origins; in practice, that means they must be `file://` URLs.  There is support for https://www.npmjs.com/package/asar built into Electron, which might help.  Or we could fetch entire branches using github's archive endpoint, possibly converting to asar on the fly.

**Comment by ncalexan** [comment]
@canuckistani if you want to influence how this looks and feels, or what it enables, please give direction.

**Comment by victorporof** [comment]
This sounds awesome!

**Comment by victorporof** [comment]
I believe this should be duped to https://github.com/mozilla/tofino/issues/905
