### ISSUE TITLE
"We've detected you're using an older version of chrome"

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#19]
When on google.com, we get a message we're using an old Chrome. This is no doubt super confusing. Maybe just a user-agent thing.

![screen shot 2016-04-06 at 10 18 27 am](https://cloud.githubusercontent.com/assets/641267/14326017/ef17399c-fbe0-11e5-9acd-40075930a131.png)

**Comment by miketaylr** [comment]
Yep, welcome to the world of non-Google blessed Chromium UA strings (see also, Opera, Yandex, Vivaldi).

**Comment by victorporof** [comment]
This is great.

**Comment by Mossop** [comment]
I don't see this anymore, I suspect it has been fixed by an update for electron, they've been bumping chrome versions pretty rapidly.
