### ISSUE TITLE
Logging in on twitter.com doesn't work

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#193]
Looks like we're not handling redirects properly? There's a spew of `command {"payload":{"url":"https://twitter.com/"},"type":"PROFILE_COMMAND_VISITED"}` when trying to log in. @ncalexan maybe you know what's up?

**Comment by ncalexan** [comment]
I do not think we're handling redirects properly; but this spew is because
we can't yet differentiate between iframe loads and main frame loads.
These are just telling the profile, "I visited here", and then after the
redirect, "I visited here".

**Comment by Mossop** [comment]
This is just a bug in electron: https://github.com/electron/electron/issues/3471

**Comment by Mossop** [comment]
Looks like Electron are waiting for a new Chrome refactor to happen which is tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=368813.

Given the number of blocking bugs I wouldn't expect us to see this fixed until after our three months are up so I think we should fork electron to just take the fix ourselves.
