### ISSUE TITLE
Expose webpack failures when running in dev mode

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#20]
Right now, if there's a build failure when running `gulp run-dev`, we just get a useless 404 error for `static/built/browser.js`.

When running in `gulp run`, we can open the tools and see "Uncaught Error: Cannot find module "./navbar/navbar.jsx". We need to display this information somewhere.

**Comment by jsantell** [comment]
The new build scripts don't report any errors if webpack build fails, and just fails silently.

**Comment by jsantell** [comment]
Didn't mean to close

**Comment by victorporof** [comment]
Could it be because we're using promises for build tasks now, and not catching the errors anywhere? Currently the promises should reject for everything wrong thay happens, but those rejections get swallowed. I'll tale this.
