### ISSUE TITLE
Consider whether session starts should be typed events

### ISSUE THREAD

**Issue by rnewman** [mozilla/tofino#226]
Currently a session can have a `parent` (a window, most likely) and a `source`. The source is another session, optional so the first can be *de novo*.

If it's valuable, we can also attach a type here. For example, new sessions — new tabs — could arise through Open In New Tab, or through restoring a task, or by creating a new window, or through a popup, or…

If those things will be useful for improving the browsing experience, we should start recording that data.

See also #225.

**Comment by rnewman** [comment]
@ncalexan, you were looking at this yesterday, I think; FYI.

**Comment by jsantell** [comment]
No longer necessary
