### ISSUE TITLE
Tab's loaded status doesn't always get updated

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#239]
When you open a whole bunch of tabs and then close out most of them, the tabs that were opened earlier won't have their loaded status updated.

![tabs](https://cloud.githubusercontent.com/assets/105464/14724755/25816f1e-07e6-11e6-9682-27f01022ae0c.gif)

**Comment by victorporof** [comment]
This should be fixed now in the new frontend. Please reopen if not.
