### ISSUE TITLE
AssertionError when deleting a tab

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#247]
STR:
- add multiple tabs
- delete a tab using Cmd-W and then try to delete others

The following error shows up in the console:
```
tofino/node_modules/redux-logger/lib/index.js:221 Uncaught AssertionError: Page 6717b441-1389-414c-8475-c7d615d4a9ae not found in current state
```

**Comment by linclark** [comment]
This seems to be `setPageDetails` passing in an invalid id somewhere.

**Comment by linclark** [comment]
This seems to be intermittent. It mostly happens when I'm using Cmd-W, but if I am closing out tabs fast with the X, it happens too.

**Comment by jsantell** [comment]
I'll check this out
