### ISSUE TITLE
Use connect() for Page components to reduce wasted time

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#253]
Pages change pretty frequently. Whenever a user rolls over a link, `page.statusText` will change. Whenever a user types, `page.userTyped` will change.

Currently, we are diffing the whole tree when a page changes. We should be able to make this more efficient without too much work.

We are using connect() in one place, at the top of the tree, and we’re accessing the whole state tree. Redux automatically implements `shouldComponentUpdate()` for any container components (the higher order component that is returned from a call to `connect()`). However, it does not do that for the children. This means that a change to state causes the whole component tree to go through `_performComponentUpdate()`, which results in wasted time doing render tree construction and virtual DOM comparisons that do not result in a DOM modification

If we split this up and have containers at lower levels, we should see less wasted time in the perf tool. The basic concept of this is explained in a talk from [React.js Conf 2015](https://www.youtube.com/watch?v=KYzlpRvWZ6c), and Dan Abramov recently provided an [example of doing it with Redux](https://twitter.com/dan_abramov/status/719723513016426496).

There was some concern in the React components meeting that this would cause forced updates. It [does not cause a call to `forceUpdate()`](https://github.com/reactjs/redux/issues/1303#issuecomment-188618535). Instead, it works with React’s dirty component queue. It will check each connected component and if it’s possible that it will need an update, it will add it to the dirty component queue. This means that connected components can be added to the queue independent of their parents.

@jsantell @victorporof & anyone else, let me know if you want to talk through this before I start.

**Comment by jsantell** [comment]
Would this mean that we have to separate out top level state so that App/Browser do not receive the page states at all?

Currently what we have:

* App
  * Browser
    * NavBar
    * TabBar
    * [Pages] 

If we move Pages up to a higher level component, and has access to it's corresponding page state, could the other components (navbar, for example) access it? Or I guess we could dupe it in the main state when we change current page.

I think this is a great idea, and interested in knowing how this'll change things

**Comment by linclark** [comment]
Good question, I had been thinking about this too.

NavBar does need to sometimes change in response to page actions. I believe the only one that matters for it is the length of the pages list. To handle this, we'd possibly make NavBar a connected component, too. In it's `mapStateToProps`, it could query for the number of pages. But I need to dig in a little more to be sure.

These connected components (App, Page, NavBar) would stay at their current levels in the component tree. The difference is that all of them would have direct access to values in the store (and we would make all of the `mapStateToProps` functions more specific).

**Comment by jsantell** [comment]
NavBar could probably get away with only the current page -- we do need to respond to changes in nav capabilities (canGoBack, canRefresh, etc), and the TabBar would need the page list, titles/status of current page

**Comment by jsantell** [comment]
Made redundant via #282
