### ISSUE TITLE
Establish dedicated BrowserWindow for main process communication

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#27]
A number of things are exposed to content processes via HTML5 APIs, but not directly to the main process.  (For example, https://github.com/electron/electron/blob/master/docs/tutorial/online-offline-events.md.)

Rather than negotiating 0/1/many content windows, I suggest we add a single long-lived hidden rendering process to handle funneling HTML5 APIs to the main process.

**Comment by jsantell** [comment]
For non-BW specific states, like online/offline, this sounds great; are there any other APIs that you think would be useful to have in the main process?

**Comment by jsantell** [comment]
This issue is no longer relevant I believe. Please reopen if you feel otherwise.
