### ISSUE TITLE
Have an about:license page

### ISSUE THREAD

**Issue by joewalker** [mozilla/tofino#293]

**Comment by Mossop** [comment]
I suspect we can't use about:license. I think chromium reserves that protocol. tofino:license might work though.

**Comment by joewalker** [comment]
We're going to have to make it clear whose licenses are whose, so some form of edit to the chromium about:license feels inevitable, even if it's just to remove it.

**Comment by jsantell** [comment]
Dependent on #296 (but may not be `about:*` like @Mossop mentioned)

**Comment by Mossop** [comment]
I might have been mistaken and thinking of `chrome:`. loading about:license just goes to ddg right now so chromium probably isn't doing anything there.

**Comment by jsantell** [comment]
What are our requirements here? List of every npm dependency and license? Chromium's licenses? @joewalker @canuckistani
