### ISSUE TITLE
Moving pieces around to match mockups

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#3]
Moving the NavBar to the top, and TabBar below, and moving buttons around to match the mockups. TabBar will eventually be hidden like the mockups and revealed with the "Pages" button.

Working on this now.

**Comment by digitarald** [comment]
How could one access the mockups to contribute?

**Comment by jsantell** [comment]
Last piece here https://github.com/mozilla/tofino/pull/51

And good call @digitarald, I'm not sure if there are any more permanent, public places for the mockups for now (but ping in slack for credentials)
