### ISSUE TITLE
The main menu isn't available on Windows

### ISSUE THREAD

**Issue by Mossop** [mozilla/tofino#305]
Either because it is OSX only or because we've hidden the titlebar or something but the menu that we're making changes to isn't visible to windows users. We must fix that or remove it and use something else that Windows users can see.

**Comment by bgrins** [comment]
See: https://github.com/electron/electron/blob/master/docs/api/menu.md#setting-menu-for-specific-browser-window-linux-windows

**Comment by bgrins** [comment]
win.setMenu: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetmenumenu-linux-windows

**Comment by Mossop** [comment]
Ok so this only works if we turn on the default OS window frames:
![capture](https://cloud.githubusercontent.com/assets/437326/15120395/68ddabb4-15ca-11e6-89ef-1326fe5e0e0a.PNG)
