### ISSUE TITLE
Tab closing leaves orphan page, closes tab bar

### ISSUE THREAD

**Issue by rnewman** [mozilla/tofino#307]
* Start browser.
* Navigate to a URL. 
* Click 'Pages'. You'll see a tab, with the page title.
* At some point the title changes to 'Loading…'. That's bug number 1.
* Click the 'x' on the tab.

Actual:
* If this is the last tab, the tab bar goes away.
* The current page stays open.
* The URL bar says 'New Tab'.
* If you reopen the tab bar, the tab is titled 'New Tab'.

Expected:
* The tab bar always stays open.
* The current page closes and is replaced by a new tab.

**Comment by linclark** [comment]
I might be able to fix this as part of the work I'm doing in #283

**Comment by bgrins** [comment]
This is now fixed
