### ISSUE TITLE
clicking on article links in google news doesn't open the link

### ISSUE THREAD

**Issue by canuckistani** [mozilla/tofino#330]
See my gif

![gnews-links-not-working](https://cloud.githubusercontent.com/assets/104315/14996698/245ee348-1130-11e6-8a30-a3e1d5d52592.gif)

Note that right-click, open in new tab does work, and other sites like ars work.

**Comment by Mossop** [comment]
@canuckistani Can you retest this, it seems to work for me now.

**Comment by jsantell** [comment]
Also WFM, please reopen if the issue persists
