### ISSUE TITLE
OS X: Closing Window Leaves App Useless

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#335]
Closing the browser window on OS X keeps the app open but without a way to open a new window, thus leaving the app in a weird limbo.

**Comment by jsantell** [comment]
Thanks David!
@canuckistani what's the expected functionality here?

**Comment by canuckistani** [comment]
@jsantell on OS X the expected behaviour is that the full app menus are still available and that you could open a new browser window via File -> New Window or CMD+N.

I don't consider this high priority.
