### ISSUE TITLE
App Menu: New Tab, New Window

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#339]
Tracking for MVP milestone, both hotkeys and menu items.

I believe these are mostly working, but should not be considered complete without tests, as fragile as hotkeys are to begin with.

**Comment by jsantell** [comment]
New Tab works, New Window does not, in either File menu, or hamburger menu

**Comment by victorporof** [comment]
These work now in the new frontend. There are many parts of our code not being tested at the moment, so we should defer to https://github.com/mozilla/tofino/issues/657 instead of these individual issues that may get lost.
