### ISSUE TITLE
Tests should throw when PropType validation fails for a react component

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#35]

**Comment by victorporof** [comment]
@linclark do you know of any way react could notify us when a proptype validation fails, so that we may fail the tests automatically?

**Comment by victorporof** [comment]
Also, note that now that we're using babel-preset-react-optimize in production mode, these prop types are deleted from production builds, which we're actually using for tests.

Should we test builds in development mode instead? Or have yet another build configuration which is for tests only, mostly the same as production but without babel-preset-react-optimize?

**Comment by victorporof** [comment]
Found a middleground approach, see the PR.
