### ISSUE TITLE
Expose/separate browser devtools from web devtools

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#350]
I went to "Tools > Toggle Developer Tools" and somehow Web Inspector loses context and I end up with a representation of the Tofino internals and not the page/site itself:

<img width="1501" alt="webview" src="https://cloud.githubusercontent.com/assets/46655/15003486/f223c640-1171-11e6-9754-9e800117df17.png">

**Comment by jsantell** [comment]
We should probably be explicit that this is for browser development, not web development and expose a traditional web dev tools option here as well (and rename the current one)

**Comment by bgrins** [comment]
I think we should use a different shortcut for the 'browser toolbox' version (maybe cmd/ctrl+alt+shift+i), and possibly have it auto-open when running via `npm run dev`.  Then keep the current shortcut reserved for the web page inspector.

**Comment by victorporof** [comment]
Right-click and 'Inspect element' already works. We might want to have better UI for this though at some point.
