### ISSUE TITLE
Address Bar Context Menu - "Paste" and "Paste and Go" Don't Work

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#356]
On Mac OS X El Capitan the "Paste" and "Paste and Go" address bar context menu items do nothing -- the address bar stays empty after clicking either item.

**Comment by darkwing** [comment]
I see the problem but don't see the solution;  `setUserTypedLocation` is being called within `external.js` with an object as the first and only argument, yes `setUserTypedLocation` expects two arguments; `pageId` and `payload`.  I don't see how to grab the pageId yet;  also, the payload object's `userTyped` should be renamed to `text`

**Comment by bgrins** [comment]
The issues in https://github.com/mozilla/tofino/issues/356#issuecomment-216995826 are indeed problems, but even with the fix it's not setting the input value properly (b/c the input value isn't managed by react).  Always setting the input value to match userTypedLocation doesn't work quite right b/c it causes issues with the input value as the user types (the main entry point for userTypeLocation changing).  I'll take a look at it
