### ISSUE TITLE
Sourcemaps are only built for files during development builds

### ISSUE THREAD

**Issue by Mossop** [mozilla/tofino#357]
Right now we only build sourcemaps when transpiling files for development builds but we also skip transpiling files if they haven't changed since the last time. To make matters worse, test runs do a non-development build.

So a file will only have a valid sourcemap if you do a development run immediately after changing it.

We should probably just always do source maps, since they aren't embedded I don't think it buys us much.

**Comment by Mossop** [comment]
Fixed by #525

**Comment by victorporof** [comment]
@Mossop Actually fixed by https://github.com/mozilla/tofino/pull/522
