### ISSUE TITLE
back/forward buttons sometimes don't reflect history

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#361]
I've seen this happen in two different ways:

1. Click back a few, then click forward. The forward button doesn't go forward to the last page. Instead it stops at the second to last.
2. Click back all the way to the end. The back button gives you one more press backwards then it should and it loads some other page from your history.

This gif shows issue 1. I navigate a few pages (ending up on Gmail) then click back to start page. When I click forward, I can't get back to Gmail.
![tofinio-nav](https://cloud.githubusercontent.com/assets/105464/15030797/6f7a82a4-1222-11e6-92a2-5a1707a9aad5.gif)

**Comment by Mossop** [comment]
@linclark Is this still happening? I can't reproduce it.

**Comment by linclark** [comment]
I can't reproduce it now either. I'm going to close it since we can always reopen if it comes up again.
