### ISSUE TITLE
location bar of new tabshows previous tab's url

### ISSUE THREAD

**Issue by canuckistani** [mozilla/tofino#375]
STR:

1. open browser, load google news
2. hit ctrl+t to open a new tab, then click in the location field

ER: some tofino:// uri page
AR: google news url

**Comment by bgrins** [comment]
Taking a look

**Comment by bgrins** [comment]
This was fixed by https://github.com/bgrins/tofino/commit/1dbe7c330fffb2bd5ca56806938e4b915d22854d
