### ISSUE TITLE
Implement an 'under construction' theme

### ISSUE THREAD

**Issue by canuckistani** [mozilla/tofino#386]
Tofino is not supposed to be a showcase for innovative visual design during the current phase of development, so I would like the current theme to be changed to more explicitly / visually communicate to the user that what they are using is a prototype and not a finished product. 

Some ideas that have been bounced round are:

- 'sketchy' napkin drawing look
- blueprint-ish look
- [under construction](http://www.textfiles.com/underconstruction/)

I think it's too easy to get proscriprive here and say 'just add animated cartoon hard hats everywhere'. Instead, the requirement is 'provide a visual design that balances usability and the impression, perhaps whimsically, that this thing ain't finished yet'.

**Comment by canuckistani** [comment]
current status - @phlsa  is going to create some mockups of an 'under construction' theme to base this on

**Comment by phlsa** [comment]
Here's a shot at a blueprint-like theme. You can re-use the current assets for buttons but just inverted.
![blueprint ui](https://cloud.githubusercontent.com/assets/514315/15177465/7f103724-1770-11e6-96d0-4e5f77d15ed9.png)

And here's the grid texture in 1x and 2x (white on transparent background):
![texture 2x](https://cloud.githubusercontent.com/assets/514315/15177502/acbd27c2-1770-11e6-94a9-93be9c1dac22.png)
![texture](https://cloud.githubusercontent.com/assets/514315/15177503/accc1a66-1770-11e6-970f-d93ceff24b75.png)

**Comment by victorporof** [comment]
Nice! On it!
