### ISSUE TITLE
Add screenshot in the readme

### ISSUE THREAD

**Issue by Mte90** [mozilla/tofino#396]
Like https://github.com/browserhtml/browserhtml it is very helpful a screenshot or gif to see the actual version without download everything and try it to see the status.

**Comment by jsantell** [comment]
To be honest, there isn't quite much to see yet

**Comment by Mte90** [comment]
as i can see on twitter there are different screen but without is too difficult to see what is tofino

**Comment by ncalexan** [comment]
@canuckistani has asked for an "under construction" theme and might not want too many specific artifacts on the main page.  Jeff?

**Comment by canuckistani** [comment]
Yeah, this should be blocked on #386

**Comment by Mossop** [comment]
I don't think we can do this given how quickly we are changing things this would get out of date too quickly. Before too long we should have builds available to download which should make it significantly easier to see what it looks like.

**Comment by Mte90** [comment]
Just as reference few screen from twitter:

https://twitter.com/jsantell/status/723265275911540737
https://twitter.com/projecttofino/status/733769445596794880

**Comment by victorporof** [comment]
The current look has nothing to do with what we might end up shipping.
