### ISSUE TITLE
Make hotload not bring App to the foreground

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#40]
I hit save in Emacs, a lot.  I manage my git tree in Emacs, a lot.  We hot reload the App front-end even when it's not the foreground App; and that brings the window to the front.  Can we not do that?

**Comment by bgrins** [comment]
What platform is this on?  I don't see it re-focus the app on osx when saving with `gulp run-dev`

**Comment by ncalexan** [comment]
On Thu, Apr 7, 2016 at 5:26 PM, Brian Grinstead <notifications@github.com>
wrote:

> What platform is this on? I don't see it re-focus the app on osx when
> saving with gulp run-dev
>

OS X.  It's consistent; I can investigate further if it helps.

**Comment by bgrins** [comment]
I agree that hot-reloading should never refocus the app, not opposed to removing that behavior at all

**Comment by jsantell** [comment]
Yeah this sucks. :+1:
