### ISSUE TITLE
Use ChromeDriver's `waitUntil` method rather than our own

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#414]
We have some polling mechanisms in the webdriver tests, and when we hit a timeout, the polling doesn't stop. We would also get for free the driver's timeout limit (10s), which per polling-point, is sufficient and will cause tests to fail sooner (which is what we want in a 'correct' timeout scenario). May fix cascading failures and highlight real failures easier.

**Comment by victorporof** [comment]
@jsantell Can we not use the `waitUntil` function that landed https://github.com/mozilla/tofino/commit/97559cb8f035890b07fe705d54b15fc1401ea366 Alternatively, I'd be happy with using whatever else, as long as we have _something_.

**Comment by jsantell** [comment]
This was specifically for webdriver tests, not any other tests

**Comment by victorporof** [comment]
Can't we use that same method for all test types?

**Comment by Mossop** [comment]
Looks like this went away with most of the webdriver tests.
