### ISSUE TITLE
`npm start` runs the build in dev mode

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#428]
The way `build-config.json` is now written has changed. If a property is missing, it's not overwritten as `false`, but the old value is reused.

**Comment by victorporof** [comment]
One more reason for https://github.com/mozilla/tofino/issues/429

**Comment by victorporof** [comment]
@Mossop is there a reason this is the way it is? Why aren't we nuking build-config.json when writing to it in task-config-builder.js? Why are we reusing the old config?

**Comment by Mossop** [comment]
We cache the versions of modules that electron-rebuild has made in there and we need to persist that or we'll rebuild more often than we have to. We could cache that somewhere else though.

I thought we were explicitly overwriting with defaults each time already though.

**Comment by Mossop** [comment]
What effect are you seeing here, Any chance this is just #357?

**Comment by victorporof** [comment]
I'm seeing `npm start` running the build in dev mode, instead of production mode.

I can easily fix this by just adding { development: false } in the buildDev task. But I'm very wary of this getting completely out of hand as we keep adding build options.

**Comment by Mossop** [comment]
So the defaults for all values are set in `BASE_CONFIG` in `task-config-builder.js`, values there overwrite whatever is in the existing build-config.json and are then overwritten by any properties passed to the config task. Apparently I misread and assumed the default for development was false when I made the changes.

As long as we keep BASE_CONFIG up to date with defaults for any new properties we add then we should be fine. The alternative is to blow things away everytime and do something else to persist the module versions across. I don't mind which really.

**Comment by victorporof** [comment]
Hmm, that's a good point. But what does 'default' mean? A default for one kind of build should maybe be different from the default of another. Or should we user 'release' as the default build?

**Comment by Mossop** [comment]
I don't know if it is worth spending too much time on this. I don't think we plan to add much more build settings, we should just set the default to be non-development to solve this and come back to this if we find we're still having issues later.

**Comment by victorporof** [comment]
sgtm
