### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#43]
There's a .travis.yml file here: https://github.com/mozilla/tofino/blob/master/.travis.yml, but https://travis-ci.org/mozilla/tofino appears to not be set up.

**Comment by Mossop** [comment]
This was from some old work, I was going to tinker with getting it going tomorrow. More important probably is appveyor as we're targetting Windows primarily right now.

**Comment by jsantell** [comment]
Both travis (OSX/Linux) and appveyor (Win) are now implemented, closing
