### ISSUE TITLE
Extract main process Profile service

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#44]
Right now, there's a global set of bookmarks shared between `BrowserWindow` instances via IndexedDB.  This approach doesn't address Sync (in the future) well.  @rnewman has written about this in https://github.com/FractalBrew/blueharvest/wiki/Profile-service (currently (temporarily?) private).

This ticket tracks fleshing out a main process profile service, fleshing out the IPC required to move between the two, and moving the existing approach to the new hotness.

**Comment by rnewman** [comment]
See https://github.com/mozilla/tofino/wiki/Profile-service

**Comment by rnewman** [comment]
This is done.
