### ISSUE TITLE
Consider using Flow or TypeScript

### ISSUE THREAD

**Issue by LegNeato** [mozilla/tofino#46]
Types help large projects maintain sanity. I saw this on on a large Electron/Atom-based project (https://github.com/facebook/nuclide/). Consider using typed JS from the start to keep the code sane. I would suggest Flow as you can do gradual typing, replaces React proptypes, etc...but please, use something!

**Comment by ncalexan** [comment]
For the record, I'm 100% in favour of this, but I've been writing a lot of Java lately...

**Comment by victorporof** [comment]
JSX with typescript is really really nice. I'd also be in favor of doing this, but I wonder how much runtime overhead we'll get out of the generated output. Things are already a bit sad with all the babeling that we're doing, but we can hope for not having to do that anymore once the js engine catches up.

**Comment by victorporof** [comment]
@joewalker @jsantell What do you think about at least using Flow for now?

**Comment by ncalexan** [comment]
@victorporof can I get a brief breakdown on pros and cons of Flow vs. TS?  (Link is fine.)

Is it possible to use neither of, one of, or both of, the options in the main process?  If one works well with Node.js and the other doesn't, I'd argue for consistency across environments.

**Comment by jsantell** [comment]
Main process uses gulp (runtime, need to do it a build time #14), so adding this or something would still require a build step. I think @Mossop wanted it to be as close to "future JS" as possible, though.

That being said, I'd be fine with using TS or something (why Flow over TS? I'm not that familiar with either); FWIW, browser.html also uses Flow.

**Comment by linclark** [comment]
Flow is a project being developed at Facebook. It has built in support for propTypes. Using it should remove the need for #35

**Comment by LegNeato** [comment]
Also note that Flow is integrated with Babel so type annotations can be stripped away or converted to comments in the code. You can also only partially type your code if you don't want to require types (gradual typing) but I would suggest not doing that.

**Comment by canuckistani** [comment]
@victorporof "but I wonder how much runtime overhead we'll get out of the generated output." could we run tests and see what the overhead actually is?

**Comment by victorporof** [comment]
@ncalexan 

Flow aims to add type annotations to javascript and simply doing static analysis. As @LegNeato pointed out, it's nicely integrated with babel (which we already use), and the type annotations can be removed. It will add no runtime overhead.

TypeScript is its own language and requires transpiling. It will absolutely add runtime overhead, probably comparable to what we already have by transpiling es6/7 to whatever's supported by node 5.

It's probably possible to use both for the main process, the only difference is that with Flow it's just a matter of commenting out the type annotations before running, while TypeScript requires transpiling.

I vote for using Flow.

**Comment by victorporof** [comment]
@canuckistani If we end up deciding that TypeScript is better than Flow for our particular usecase, then I could do some benchmarking. However since we're only interested in types, these can be enforced just by static analysis which Flow does.

**Comment by Mossop** [comment]
I'm averse in general to non-standard JS languages like coffeescript etc. since it moves us away from "build like the web" further than I think we should go. But I like that Flow is minimal and optional and already integrated into the tools we use. Types are a pretty powerful way to assert program correctness that I've always found to be incredibly useful in XPCOM if you can believe that so it seems like a good idea to add some static checking here. I also like that it compiles away so no runtime overhead other than what we already have from babel (which hopefully should be small already since we're only applying the transforms that node 5 needs which isn't a lot).

So I have no objection to using Flow if that makes sense. I would echo @ncalexan that we really must be in a place where we use can use the same syntax in whatever code we write. Having to remember which process code will run in is going to lead to mistakes not being caught so lets make sure the main process gets this loving too.

**Comment by victorporof** [comment]
I'll start looking into this.

**Comment by shybyte** [comment]
@ncalexan @victorporof If you use transpile TypeScript to ES6 it is also mainly removing the type annotations. If you transpile to ES5, both TypeScript and Babel transform the code deeply. In this regard there should be no difference to Flow and no difference in runtime overhead. 

Flow has deeper type inference than TypeScript. It will find the bug in this code without any type annotation (which you could add if you want):
```
function length(x) {
  return x.length;
}

length(10)
```

TypeScript has a lot of type inference but not as deep as Flow, so you would have add a type annotation to find the bug.

```
function length(x: string) {
  return x.length;
}

length(10)
```

On the the other hand, often explicit type annotations can make the code more readable and allow better editor/IDE support, which is pretty good for TypeScript.

Quoting http://www.hammerlab.org/2015/12/09/our-experiences-with-flow/:
_Both Flow and TypeScript are good choices for a new project. Flow is a more sophisticated type system, with better support for patterns like type unions and nullable types. TypeScript is more established and has better support, e.g. more editor plugins and third-party type definitions._

(TypeScript will catch up with (non-)nullable types in the 2.0 version.)

**Comment by jsantell** [comment]
Is there any possibility of annotating via comments like Google Closure(?) which enforces checks at build time? Possibly best of both worlds, leaving it still JavaScripty as it's just comments, but get the type enforcement?

**Comment by linclark** [comment]
I don't have experience with Google Closure, but I believe that Flow enforces checks at the same time. It is a static type checker, so the analysis happens at "compile" time.

**Comment by victorporof** [comment]
Yes, flow doesn't do anything runtime. IMO there's no real difference between annotating via comments and annotating via :type.

**Comment by shybyte** [comment]
I have worked with the Google Closure compiler in the past and work currently with TypeScript and while the Google Closure was better than nothing, it felt always clumsy/noisy/boilerplaty. For example there is no syntax in javasscript to declare an interface, so you have to misuse existing javascript syntax:
```
/**
 * @interface
 * @template T
 */
function Stack() {};

/**
 * @param {T} value
 */
Stack.prototype.push = function(value) {};

/**
 * @return {T} 
 */
Stack.prototype.pop = function() {};
```

In TypeScript you can write much more concise:

```
interface Stack<T> {
  push(value:T)
  pop(): T 
}
```

IMO this is a "real" difference.

**Comment by victorporof** [comment]
@shybyte That makes sense, from the perspective of having to write such copious amounts of comments, type annotations in Flux are easier on the eyes.

**Comment by victorporof** [comment]
Luckily flow can work with eslint as well, which we now use extensively: https://www.npmjs.com/package/eslint-plugin-flowtype

**Comment by ncalexan** [comment]
@victorporof here's a placeholder Flow configuration.  I didn't try to actually run this in automation, for example, so there's lots more to be done.  But it's a start!

Run `flow check` in the main source directory to try it out.
