### ISSUE TITLE
Can't run Tofino

### ISSUE THREAD

**Issue by nt1m** [mozilla/tofino#491]
Did:
- `npm install`
- `npm start`

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.9.2
3 info using node@v6.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tofino@0.1.0~prestart: tofino@0.1.0
6 silly lifecycle tofino@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle tofino@0.1.0~start: tofino@0.1.0
8 verbose lifecycle tofino@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle tofino@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/admin/code/mozilla/tofino/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle tofino@0.1.0~start: CWD: /Users/admin/code/mozilla/tofino
11 silly lifecycle tofino@0.1.0~start: Args: [ '-c', 'node build/main.js --run' ]
12 silly lifecycle tofino@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle tofino@0.1.0~start: Failed to exec start script
14 verbose stack Error: tofino@0.1.0 start: `node build/main.js --run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid tofino@0.1.0
16 verbose cwd /Users/admin/code/mozilla/tofino
17 error Darwin 15.0.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.2.0
20 error npm  v3.9.2
21 error code ELIFECYCLE
22 error tofino@0.1.0 start: `node build/main.js --run`
22 error Exit status 1
23 error Failed at the tofino@0.1.0 start script 'node build/main.js --run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the tofino package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/main.js --run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs tofino
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls tofino
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rnewman** [comment]
Did you try `npm run dev`?

**Comment by nt1m** [comment]
@rnewman It doesn't work either.

**Comment by victorporof** [comment]
What about on a fresh clone?

**Comment by nt1m** [comment]
@victorporof Not working either. The logs are the same as above.

I'm on OSX 10.11 if that helps

**Comment by victorporof** [comment]
npm list -g --depth=0
?

**Comment by nt1m** [comment]
@victorporof 

/usr/local/lib
├── bower@1.7.2
├── chrome-tailor@0.0.5
├── crx2ff@0.5.4
├── eslint@2.9.0
├── eslint-plugin-html@1.4.0
├──  -> /Users/admin/code/mozilla/fx-team/testing/eslint-plugin-mozilla error: ENOENT: no such file or directory, open '/Users/admin/code/mozilla/fx-team/testing/eslint-plugin-mozilla/package.json
├── eslint-plugin-react@4.2.3
├── grunt-cli@0.1.13
├── gulp@3.9.0
├── gulp-cli@1.2.1
├── jpm@1.0.2
├── npm@3.9.2
├── svgo@0.6.4
└── webpack@1.10.5

npm ERR! error in /usr/local/lib/node_modules/eslint-plugin-mozilla: ENOENT: no such file or directory, open '/Users/admin/code/mozilla/fx-team/testing/eslint-plugin-mozilla/package.json'
npm ERR! extraneous: escope@3.3.0 /usr/local/lib/node_modules/eslint-plugin-mozilla/node_modules/escope
npm ERR! extraneous: espree@2.2.5 /usr/local/lib/node_modules/eslint-plugin-mozilla/node_modules/espree
npm ERR! extraneous: sax@1.1.4 /usr/local/lib/node_modules/eslint-plugin-mozilla/node_modules/sax

**Comment by Mossop** [comment]
What does `node build/main.js --run` display?

**Comment by victorporof** [comment]
Did `npm install` exit cleanly?

**Comment by nt1m** [comment]
@victorporof Yes.
@Mossop Will try when I'm back home

**Comment by jsantell** [comment]
Many things have changed in a short time -- closing this for now, please reopen if the issue persists
