### ISSUE TITLE
Sometimes appveyor builds fail when a new node version is required

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#496]
See https://github.com/mozilla/tofino/pull/489#issuecomment-220888635

**Comment by victorporof** [comment]
Welp, I merged those greenkeeper PRs and builds are now failing https://ci.appveyor.com/project/Mozilla/tofino-u1hv8/build/1.0.431/job/9y1lxt6ii16v4oyg :(

@Mossop

**Comment by Mossop** [comment]
I respun that build and it passed. See #498
