### ISSUE TITLE
Builds fail on a fresh clone

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#497]
`npm install` fails: https://pastebin.mozilla.org/8872691

Apparently `node-gyp rebuild` doesn't work.

😢

**Comment by victorporof** [comment]
@Mossop looks like you might be able to help?

**Comment by victorporof** [comment]
Maybe related to https://github.com/mozilla/tofino/issues/491 ?

**Comment by victorporof** [comment]
`npm run` then tells me 

```
> tofino@0.1.0 start /Users/victorporof/Work/Mozilla/tofino
> node build/main.js --run

Dependency checks failed.
electron-rebuild: not installed!
Invoke npm install to install missing packages
```

**Comment by victorporof** [comment]
Simply installing python 3.5.1 fixed it...

**Comment by victorporof** [comment]
If we require python 3 as a dependecy or build stage for some reason, we should add that to the readme. Or maybe have more helpful error messages.

**Comment by Mossop** [comment]
I don't think we need python 3.5 but do need a python, probably at least some version of 2.7.x. What version did you have previously?

**Comment by victorporof** [comment]
Having just 2.7.11 installed, I got the errors mentioned in the pastebin. Maybe installing python 3 also installs some dependencies that we need?

**Comment by victorporof** [comment]
Figured it out: `brew install python3` also installs `openssl`. Running `brew edit python3` shows the formula that confirms this. OpenSSL is used while running `node-pre-gyp install --fallback-to-build` to compute sha1 and/or md5 hashes. The code complains that there's no modules available that do that, since python 2.7 doesn't come with openssl by default.

🙌

**Comment by Mossop** [comment]
That's odd, the hashlib docs say that sha1() and md5() are always available regardless of installed openssl version

**Comment by victorporof** [comment]
https://github.com/mozilla/tofino/commit/e579c136421b61dcf9e32069d96b1559edf7bb41

**Comment by Mossop** [comment]
`brew edit python` shows that python 2 in homebrew also requires openssl so I'm not sure how you got into a state without it but it shouldn't affect most folks. Also it is unnecessary to install python through homebrew, OSX ships with a usable python and openssl which are used by default.

**Comment by victorporof** [comment]
In that case, what happened to me was very weird, and for some reason required me to manually install openssl. The python 2.7 formuae indeed lists openssl as a "recommended" dependency, rather than "mandatory", which might be a reason why it wasn't working for me on a fresh system.

If you prefer removing the readme edits, let me know.

**Comment by Mossop** [comment]
Maybe you haven't brew updated? It shows openssl as mandatory for me.

**Comment by victorporof** [comment]
Ugh. Indeed.

**Comment by Mossop** [comment]
Anyway might as well leave the changes in, no harm in getting users a newer
version of python.

**Comment by victorporof** [comment]
Well, I didn't list python3 as a dependency, just regular python. So I guess users will get 2.7.11 from homebrew instead of using OS X's 2.7.10. 👍

**Comment by victorporof** [comment]
Anyway, making sure those system dependencies are installed is probably a good idea no matter what.
