### ISSUE TITLE
We're depending on `true-html-escape` rather than on more well known escape utilities

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#504]
Is there a reason for this? Does that module provide something more/better than other well known libs like `escape-html`[0], which are likely to be better maintained because of their popularity?

[0] https://www.npmjs.com/package/escape-html

**Comment by victorporof** [comment]
@ncalexan you added this dependency

**Comment by ncalexan** [comment]
@victorporof, in fact @rnewman did, and I know that he filed https://github.com/component/escape-html/issues/23 precisely because these "better maintained" libraries are not very good :(

**Comment by victorporof** [comment]
Interesting. Closing this then.
