### ISSUE TITLE
`nvm` can't be used in fish shell

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#507]
See https://github.com/creationix/nvm/issues/303

Should our readme cater to people who don't use more well known shells like bash or zsh? If so, we should tell them to install `fnm` instead, via `fisherman` or `oh-my-fish` or whatever other shell utility package manager they use.

**Comment by Mossop** [comment]
Maybe now homebrew's default node install is actually a version of node we use we should just switch to `brew install node`.

**Comment by victorporof** [comment]
`brew install node` does install the latest node and nvm.

**Comment by linclark** [comment]
The brew install of node can cause problems for people. When I was at npm, the folks there were pretty adamant about not recommending it. Instead, the recommendation was to install/update from the nodejs.org itself. I don't know whether that's still the case.

**Comment by victorporof** [comment]
@linclark any specific kind of problems, or just the age-old "we don't maintain the formula so we have no control over what might happen"?

**Comment by linclark** [comment]
I think it was a little bit of the latter, but also IIRC it didn't set the right permissions on the global install directories. It's not too hard to change that, but it can be confusing for people who aren't familiar with npm because npm just spews `EACCES` at you.

**Comment by linclark** [comment]
Just did a little research and it looks like that isn't a problem with the homebrew version anymore, so brew should be fine.

**Comment by victorporof** [comment]
Alright, I'm updating the readme.

**Comment by victorporof** [comment]
https://github.com/mozilla/tofino/commit/62c589554bcfbfefc723d9b3e7c89f66f3bacb25

**Comment by victorporof** [comment]
Thanks @linclark for the input!

**Comment by linclark** [comment]
FYI, it seems like on Yosemite brew installs node 5.9.1
