### ISSUE TITLE
Bookmark Requests Display in History

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#511]
We should remove internal bookmark requests from the history list.

<img width="1059" alt="bookmarkhistory" src="https://cloud.githubusercontent.com/assets/46655/15506746/633a9b16-218e-11e6-85bc-b9060caccbf9.png">

**Comment by rnewman** [comment]
On consideration, I think we should continue to record these visits — it's kinda interesting if a sequence of visits starts in history or bookmarks. I could certainly be convinced that there's no value in *showing* internal pages in a linear list view.

**Comment by victorporof** [comment]
I don't think this happens anymore, might be regressed/fixed by the new frontend. Closing for now, but feel free to reopen if we should do something different.
