### ISSUE TITLE
Update docs to mention Electron 1.2.1

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#517]
We need [this fix](https://github.com/electron/electron/issues/5528) to reduce a dep on VS2015 redistributable

**Comment by jsantell** [comment]
Be sure to update docs/building.md when this is fixed

**Comment by victorporof** [comment]
We updated to 1.2.1 https://github.com/mozilla/tofino/commit/6ec5e8b7c6c11a9361aba8a8a3c335974dacbe5a

@jsantell ping
