### ISSUE TITLE
Use React for the tofino://stars page, replacing the current prototype

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#531]

**Comment by victorporof** [comment]
Part of https://github.com/mozilla/tofino/issues/518

**Comment by bgrins** [comment]
FYI - there is already a tofino://stars page.  Not sure if you want to use this issue to improve it or if you'd rather close this out

**Comment by victorporof** [comment]
Should use React in there. Rewording this issue title.

**Comment by ncalexan** [comment]
There's an interesting thing happening here, which I don't think we've really explored.  The `tofino://stars` page is _content_, rendered in a `<webview>` with an injected API.  To produce that with React is possible, and possibly beneficial -- but there's no particular tie to our existing React application.  I'd really like to try hosting these content bits (including `tofino://newtab`!) remotely, changing the React calculus yet further.

**Comment by victorporof** [comment]
[Posting our conversation here]

Definitely, tying it to our current application in any way is a clear no-no. We want this to be completely separate from the browser, and we might want to explore the possibility of serving these pages as regular privileged web content in the future ("privileged" in the sense of secure, not like how we defined "privileged" in Firefox where pages could interact with the browser). One immediate clear benefit would be ease of A/B testing for example, but this would also allow any client to consume 'user agent data' through regular https, allowing much more diverse interaction possibly with/through third parties.
