### ISSUE TITLE
Consider having a clobber argument passable to `npm install`, or a fully fledged clobber task that does everything

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#537]
@bgrins you suggested adding a clobber build command. I worried about it clashing with our clean task, and there being some overlap between the two. Looking into this a bit more, I wonder if we can avoid that problem by just having a `--force` or `--blank` or `--clobber` or whatever argument that you can pass to `npm install`, instead of manually having to `rm -r` some folders.

**Comment by victorporof** [comment]
Note that since npm is terrible with CLI arguments, the commandline invocation would look like `npm install -- clobber` or `npm install -- --clobber`.

**Comment by jsantell** [comment]
Couldn't we just have `npm run clobber`?

**Comment by victorporof** [comment]
@jsantell having both a clobber and a clean task seems a bit awkward, there might be some overlap. I'd be happy with a `npm run clobber` if it also cleaned up the dist directory like our clobber task does.

**Comment by bgrins** [comment]
I fell back to updating the docs because the task required npm packages be installed which led to a scenario where you needed to install packages in order to remove them.  This is because among other things, the build script requires babel-polyfill.  This could be updated surely by making a separate script just for clobber that uses the built in filesystem apis to remove these folders/file.

**Comment by bgrins** [comment]
As for the difference between clean and clobber, I think they are two distinct things.  IIUC, clean is for removing any previous packaged build and is run at the beginning of a package command.  If we were to expand clean to also mean clobber then that means any time you package a build it would also remove all of your node modules and other built files.

**Comment by bgrins** [comment]
I think `npm run clobber` fits in better with the rest of the tasks versus it being tied to `npm install`

**Comment by bgrins** [comment]
So we could have a build/clobber.js file with no dependencies that removes .electron, node_modules, and build-config.json

**Comment by bgrins** [comment]
clobber could also clean up the dist directory as in https://github.com/mozilla/tofino/issues/537#issuecomment-221459295, but keep in mind it couldn't directly run the clean task so if that task changed we'd need to also update the clobber implementation (if applicable).

**Comment by Mossop** [comment]
As things stand at the moment if you just clobber node_modules but not build-config.json things end up in a broken state. I've been thinking over a way to fix that that might make the need for clobber go away entirely.

**Comment by victorporof** [comment]
We have a clobber command now.
