### ISSUE TITLE
Split page state into pageIds and pages

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#544]
There have been two different PRs that addressed the full app rerendering problem in different ways. The approach in #275 approach confused reviewers, so I created #282 instead. However, the performance improvements achieved by that are hard to maintain and don't apply to all actions.

We should use the concept introduced in #275. This means having a `pageIds` array and a `pagesById` map. This will improve performance in a way that 1) is harder to deoptimize and 2) makes actions where pages are added or deleted (such as new tab) faster as well.

**Comment by victorporof** [comment]
Done in the new frontens. I didn't know about this issue being files, it's nice reaching the same conclusion.
