### ISSUE TITLE
Inactive tabs are not resized when opened.

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/tofino#55]
Inactive tabs don't seem to resize when they are shown.

Steps to reproduce:
- Start with the small browser window
- Double click on the top bar to make full screen
- Select the second tab which was opened at first load also
- Notice that the tab is the same size as the initial window

Ubuntu 16.04 and Node 5.8.0

**Comment by victorporof** [comment]
Is this still the case?

**Comment by jonathanKingston** [comment]
Can no longer replicate on the latest checked out code. Thanks!
