### ISSUE TITLE
Find/create ESLint rule forbidding creation of handlers in components' render methods

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#561]
As suggested by @victorporof in #553, we should have a rule forbidding this.

There's a good explanation of why this is a problem in [React.js pure render performance anti-pattern](https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.oosvf07x3) (see the Functions create identities too section).

**Comment by victorporof** [comment]
Added in the new frontend.
