### ISSUE TITLE
Expose <meta> events from Page <webview> elements

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#567]
Pages expose rich metadata through `<meta>` tags.  This metadata includes [Open Graph](https://developers.facebook.com/docs/reference/opengraph/object-type/article) definitions and [Twitter Card](https://dev.twitter.com/cards/types/summary) definitions.  (It doesn't include other semantic metadata like [microformats](http://microformats.org/)).

Gecko exposes such metadata with `DOMMeta{Added,Changed,Removed}`.  This ticket tracks surfacing and storing similar events, allowing to collect metadata that we may use when storing pages and especially when surfacing Page Summaries.

**Comment by linclark** [comment]
If we only use `<meta>` tags, then we'll miss a lot of the Schema.org data. Schema.org is what powers a lot of the search engine rich snippets. They don't have the requirement that you use meta tags... instead we'd need to parse the full page with a microdata/RDFa parser and also look for JSON-LD in scripts.

**Comment by ncalexan** [comment]
@linclark roger that.  Sadly there's no clear consensus on what's best for this purpose or even most widely used (see, for example, https://lists.mozilla.org/pipermail/dev-platform/2015-June/010628.html).  I expect we'll want to experiment and add additional metadata piecemeal.  This gets us good data for NYT, which is a good start :)

**Comment by linclark** [comment]
Both Open Graph and Twitter Cards are RDFa. The difference is that they have an additional requirement that things be placed in meta tags. Schema.org does not have that limitation, which is why you need to parse the full page.

**Comment by linclark** [comment]
I guess Twitter Cards will accept RDFa attribute names but does not require them. But Open Graph uses RDFa attribute names.

**Comment by ncalexan** [comment]
@mfinkle suggested https://github.com/hueniverse/metaphor, which looks pretty much like what we want, providing we can make it use the browser's Fetch APIs (for cookies/logins/etc).

**Comment by jsantell** [comment]
We're using fathom right now to handle meta parsing, so closing this as it is redundant
