### ISSUE TITLE
Use Tofino without building electron

### ISSUE THREAD

**Issue by CxRes** [mozilla/tofino#577]
Since prebuilt electron binaries are available for all platforms, could it be made possible to use those instead of having to build electron. This helps me avoid installing the ms toolchain on my windows machine just to get tofino to work...

**Comment by jsantell** [comment]
We're hoping to have distributed builds soon, once we sort some stuff out with legal/licensing

**Comment by jsantell** [comment]
I believe this is working now, using our S3 electron builds -- @bgrins @Mossop yeah?

**Comment by Mossop** [comment]
We've never had a requirement to build electron to test tofino, however you still need a ms toolchain in order to build the sqlite module that we depend on. But yes once redistributable builds are published you can test without needing to builds tofino yourself.
