### ISSUE TITLE
Should prevent transpiling of node modules

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#58]
Maybe we can do this via eslint.

Since we transpile our code before packaging, these values get turned into strings of the current machine, not the machine where a distributable is actually run. Most of the time it would be ok (like the `os.platform()` value), but there may be other discrepencies. Either way, it's a bit confusing.

If you need to query similar info, we should do it at build time -- look at `build/config-builder.js` at how the `build-config.js` is created during build time to have build-specific configurations, not runtime specific.

I'm sure I could be missing some nuisances, but this seems to make sense. How do others feel about this? Is this nothing to worry about?

**Comment by jsantell** [comment]
Not sure how most of these methods will make sense with our current build process: https://nodejs.org/api/os.html#os_os_homedir

**Comment by Mossop** [comment]
Is this a webpack thing? Can we just make it not include os (and the rest of the node modules) when transpiling?

**Comment by linclark** [comment]
I just posted a PR for discussion. If it ends up being the direction we want to pursue, I can clean it up.

It creates a custom target in the webpack config. This target is based on the "atom" one that was being used. I just excludes the `NodeTargetPlugin`. 

Currently, it just copies the options from above to pass into `FunctionModulePlugin`, but we'd want to find a better way to do that.

I haven't worked with custom targets before, so I don't know if there are any possible negative ramifications to excluding that plugin.

**Comment by victorporof** [comment]
In the meantime we also have the "no-restricted-imports" rule to disallow importing certain things: http://eslint.org/docs/rules/no-restricted-imports

**Comment by linclark** [comment]
If we don't want to exclude the whole NodeTargetPlugin, it looks like we could possibly specify how to handle node built-in modules with [more granularity](https://github.com/webpack/webpack/issues/260).

```
var webpackNode = {
  // do not include poly fills...
  console: false,
  process: false,
  global: false,
  buffer: false,
  __filename: false,
  __dirname: false
};

var webpackConfig = {
  target: function(compiler) {
    compiler.apply(
        new NodeTargetPlugin(webpackNode)
    );
  },
};
```

I'm not sure whether the [node globals](https://webpack.github.io/docs/webpack-for-browserify-users.html#node-globals) config option can do the same thing. I would assume the config option doesn't allow you to disable modules, just globals, but would be worth verifying that.

**Comment by victorporof** [comment]
My understanding is that we don't transpile node modules anymore, @Mossop is this correct? Can we close this?

**Comment by Mossop** [comment]
Yeah this isn't a thing anymore
