### ISSUE TITLE
Quick NewTab + Location Focus Issue

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#593]
I'm super excited we have this now!  https://github.com/mozilla/tofino/pull/521

Small nit:  If you open a new tab and quickly start typing an address, the location gets reset to the default history and anything you've typed is added to the end of the default address.

**Comment by bgrins** [comment]
I can confirm.  Tested this in Firefox and as AFAICT the location should not update if the URL bar is focused when it finishes loading.  If you press ESC after the load completes then it should 'revert' to the location.

**Comment by victorporof** [comment]
Duping to https://github.com/mozilla/tofino/issues/888
