### ISSUE TITLE
Disallow creation of arrow functions in component props

### ISSUE THREAD

**Issue by linclark** [mozilla/tofino#602]
It turns out the Airbnb default allows this. However, it's the same as creating a new function on each render, so that will nullify the effect of `shouldComponentUpdate()` defined on the receiving component.

We can override this in our own `.eslintrc`.

**Comment by victorporof** [comment]
I found https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

I'm going to steal this.
