### ISSUE TITLE
Frontend changes are not reflected when pressing reload shortcut

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#613]
STR:
`npm run dev`
Change something in the frontend, i.e. change BROWSER_WINDOW_STYLE to be width: 50% height: 50%
Press cmd+opt+r

Expected:
The changes are there

Actual:
They aren't, and I need to quit the process and do `npm run dev` to see them

**Comment by bgrins** [comment]
As far as I can tell, this broke with 181221d75c5ca393f804f0b7a2bc4b68f408772a (git checkout 34aec5af7e6e604b42deb676d6cea33d6256a1ee is the last known good rev here).

**Comment by victorporof** [comment]
Sorry! I'll look at why this stopped working.

**Comment by victorporof** [comment]
A typo in that commit! Thanks for bisecting @bgrins
