### ISSUE TITLE
Tofino logo icons

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#628]
We need Tofino icons (.icns, .ico) to replace the Nightly logo we have currently in `branding/app-icon.{icns|ico}`. @phlsa do we have these?

**Comment by phlsa** [comment]
Let me know if these work. The .icns converters I found are only spitting out .hqx files for some reason. I'm not an expert on OS X icon file types, so perhaps that's fine :)

[tofino-icons.zip](https://github.com/mozilla/tofino/files/302539/tofino-icons.zip)

**Comment by jsantell** [comment]
Something was up with the hqx files, but looking into it more, we can generate icns files with `iconutil` on OSX, we just need the following icon sizes:

icon_16x16.png
icon_16x16@2x.png
icon_32x32.png
icon_32x32@2x.png
icon_128x128.png
icon_128x128@2x.png
icon_256x256.png
icon_256x256@2x.png
icon_512x512.png
icon_512x512@2x.png

With those, we can add a script to generate the .icns file and put that in the tree. Thanks @phlsa !

**Comment by phlsa** [comment]
Alright, this zip should contain all the stuff you need.
I have the assets as ico and icns, but I *think* some sizes are missing there (those formats are really opaque). There's also an archive in there with all the PNG sizes you asked for, so we have that as a backup.

[tofino-icons-all.zip](https://github.com/mozilla/tofino/files/316247/tofino-icons-all.zip)
