### ISSUE TITLE
Error: EventEmitter memory leak detected. 11 ELECTRON_RENDERER_WINDOW_VISIBILITY_CHANGE listeners added

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#633]
After having 10 tabs open.

**Comment by jsantell** [comment]
We can call `emitter.setMaxListeners()`[0], as the default is 10, so I don't think it's a leak.

[0] https://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n
