### ISSUE TITLE
Don't include junk content in page summaries

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#641]
<img width="549" alt="screen shot 2016-06-07 at 2 47 54 pm" src="https://cloud.githubusercontent.com/assets/641267/15875858/eff128a0-2cbe-11e6-926c-edf010584b06.png">

I've seen this for a few sites (google.com, cnn.com), we shouldn't display any sort of code here at all.

**Comment by rnewman** [comment]
@jsantell is that the summary text for the page, the URL for the page, or a separate line item?

**Comment by jsantell** [comment]
I believe it was the summary

**Comment by rnewman** [comment]
If this was due to saved content, I'm a little surprised — I adjusted the readability code to remove all script tags. But we can make sure…

**Comment by jsantell** [comment]
We're not currently displaying page summaries.
