### ISSUE TITLE
CI is reporting success when tests fail

### ISSUE THREAD

**Issue by Mossop** [mozilla/tofino#647]
See the results at https://travis-ci.org/mozilla/tofino/jobs/135662381 for example. Even though a test timed out travis says everything worked. Appveyor is doing the same so this isn't a travis issue.

**Comment by victorporof** [comment]
I wonder if https://github.com/mozilla/tofino/pull/649 helps at all?

**Comment by victorporof** [comment]
@Mossop Found another problem: https://github.com/mozilla/tofino/pull/636#discussion_r66229583
Removing packages from package.json doesn't make the tests fail, even though packages continue to be used.

**Comment by Mossop** [comment]
@victorporof I'm pretty sure the problem is that `npm test` isn't returning a non-zero exit code in case of error, at least it seems that way when testing locally. You worked on the code that runs tests most recently, could you take a look here?

**Comment by victorporof** [comment]
@Mossop I'll have a look, but I'm not sure if any change I made could have made mocha failures not actually exit with a failure.

Regarding https://github.com/mozilla/tofino/issues/647#issuecomment-224548472 I believe it's because the node_modules folder isn't clobbered? A package was removed from package.json, but was still used somewhere else, and no test failed.

**Comment by victorporof** [comment]
Here's another example: https://github.com/mozilla/tofino/pull/652#event-686758380
CI reports everything as passing, but we were getting 403s https://ci.appveyor.com/project/Mozilla/tofino-u1hv8/build/1.0.538-svnbmaus/job/n4ycvuh03qehdbnf

**Comment by victorporof** [comment]
So https://github.com/mozilla/tofino/pull/660 should fix the originally reported problem (https://github.com/mozilla/tofino/issues/647#issue-159068329), we still have the issue of 
* node_modules folder isn't clobbered, resulting in no failures when modules are removed from package.json, but still being used in app code or tests.
* `npm install` failures (e.g. by getting 403s) aren't reported as CI failures.

**Comment by Mossop** [comment]
The node_modules thing is intentional caching to save time. We can npm
prune at the start of things though.

**Comment by victorporof** [comment]
@Mossop: so how do you feel about pruning? Expectig to take that soon?

**Comment by Mossop** [comment]
Sorry, was preoccupied with other stuff. Happy to take pruning, I can take it tomorrow if you don't want to write it.

**Comment by Mossop** [comment]
Hopefully this is fixed by #695.
