### ISSUE TITLE
Run tests both on development and production builds

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#655]
Right now we’re using a hybrid: a development build but without react-babel-optimize. Not a good idea. Should have them run both on dev and prod.

But that can get annoying locally. Maybe have that only on CI? @Mossop?

**Comment by Mossop** [comment]
I lean towards always running on production since that is the target and we should at least always do that in CI. Likewise #622.

**Comment by victorporof** [comment]
FWIW we discussed this in the meeting and the consensus was to have them both.
The current approach to have them on 'something that is like production but not quite' seems like could be an open door for problems in the future.

**Comment by Mossop** [comment]
SGTM
