### ISSUE TITLE
Hotkey: cmd/alt+left/right for history navigation

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#670]
Windows / Linux: alt+left to go back and alt+right to go forward
OSX: cmd+left to go back and cmd+right to go forward

**Comment by demoneaux** [comment]
Also adding support for backspace to go back would be great :)

**Comment by bgrins** [comment]
Recently, chrome has removed backspace for back (to prevent accidental navigation).  Interested to see if that ends up sticking
