### ISSUE TITLE
Cmd/Ctrl+L should select all the text in the URL field

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#671]
STR:
Open a tab
Press cmd/ctrl+l

Expected
URL bar is focused and text is selected

Actual
URL bar is focused and cursor is at end (no selection)

**Comment by bgrins** [comment]
This seems to only when navigation has happened outside of the URL bar, so if I open a new tab, then click a link or submit a form, then do cmd/ctrl+l I can reproduce

**Comment by victorporof** [comment]
Fixed in the new frontend.
