### ISSUE TITLE
Get rid of the `request` dependency, and just use `fetch`

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#683]
`request` is used in instrument.js and user-agent-client.js, while `request.js` is used in user-agent.js and ua.js. They seem to be serving the same purpose, although one uses the lib itself, and the other one uses `fetch`.

Why?

**Comment by jsantell** [comment]
I think we should get rid of `request` and just use fetch if we can, and it seems that `app/shared/request.js` maybe should be renamed to `user-agent-request` or something, because it does seem useful for that to be a separate lib to easily call out to the UA service

**Comment by victorporof** [comment]
Agreed. We should try using fetch as much as we can, and we already depend on `isomorphic-fetch`

**Comment by benjaminjs** [comment]
So the task is to switch the `request` usage to `isomorphic-fetch` and to rename the file `app/shared/request.js` to `user-agent-request'?

**Comment by victorporof** [comment]
@benjaminjs Yup! Although I don't think we actually need to use isomorphic-fetch, since HTML5 `fetch` is already available everywhere afaik. Basically wherever we `import 'request'`, we shouldn't.

**Comment by benjaminjs** [comment]
Awesome, I'll try to take a swing at it this evening. Thanks for the clarity, @victorporof

**Comment by victorporof** [comment]
Nice, thanks @benjaminjs

**Comment by victorporof** [comment]
The only place where this is still a problem is app/services/instrument.js which will probably get removed in https://github.com/mozilla/tofino/issues/1365

**Comment by ncalexan** [comment]
#1365 has landed, and I've checked that this is done.
