### ISSUE TITLE
We need a clever net error page

### ISSUE THREAD

**Issue by canuckistani** [mozilla/tofino#686]
Tofino currently just shows a blank page, let's do something a bit better than that.

**Comment by bgrins** [comment]
Example: load http://examplefake123.com/

**Comment by canuckistani** [comment]
Sorry, I meant error pages for when Tofino can't connect to the specified site, eg dns

**Comment by bgrins** [comment]
Also: cert errors i.e. https://expired.badssl.com/ and connection timeouts

**Comment by jsantell** [comment]
Fixed in d41cd1faee6a0e617185dec776b1e5aae7e17b05 and c11a31a8acc700d2c2040b75b1966adfe336a91a
