### ISSUE TITLE
Better URI detection for user input in nav bar

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#7]
See https://github.com/mozilla/fawkes/pull/5#issue-145877708 about coming up with a better detection for data URIs.  Here are some relevant looking utilities:

* http://mxr.mozilla.org/gaia/source/shared/js/url_helper.js
* http://mxr.mozilla.org/gaia/source/apps/sharedtest/test/unit/url_helper_test.js
* https://github.com/brave/browser-laptop/blob/master/js/lib/urlutil.js

**Comment by victorporof** [comment]
The PR landed. Closing.
