### ISSUE TITLE
Create a Tofino theme resembling Australis

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#722]
For controlled A/B testing of new features like https://github.com/mozilla/tofino/issues/518

Depends on https://github.com/mozilla/tofino/pull/720

**Comment by victorporof** [comment]
Not working on this anymore, focus is on something else.

**Comment by jsantell** [comment]
I think this is no longer a goal, correct?

**Comment by victorporof** [comment]
Not at he moment.

**Comment by victorporof** [comment]
Restarted work on this.
