### ISSUE TITLE
Clean up layout of the autocomplete dropdown

### ISSUE THREAD

**Issue by phlsa** [mozilla/tofino#740]
Our current autocomplete dropdown could use a bit of cleaning up. Here's a mockup:
![tofino](https://cloud.githubusercontent.com/assets/514315/16345598/066d3a2e-3a43-11e6-8835-b443c935eb94.png)

... and one with labels and stuff :)
![tofino-labels](https://cloud.githubusercontent.com/assets/514315/16345599/0b6f837e-3a43-11e6-893c-55d0a4227035.png)

**Comment by bgrins** [comment]
Nice, thanks @phlsa.  So we should also remove the 'page text matched' data out of results (which I believe currently shows up on a new line in a different color)?

**Comment by phlsa** [comment]
@bgrins I think we should hide it by default (keeping the result though) as a baseline. Full-text search is an interesting balancing act, since a word that occurs somewhere within the page is probably less relevant than when it occurs in the title, but showing the full text would give it more weight. That's something we'll need to iterate on.

**Comment by phlsa** [comment]
@jsantell Here's an SVG asset for the magnifying glass -- figured you might need that :)

[SearchIcon.zip](https://github.com/mozilla/tofino/files/364012/SearchIcon.zip)

**Comment by jsantell** [comment]
Thanks @phlsa, adding to #804 !

**Comment by jsantell** [comment]
Closed via #805 and #824
