### ISSUE TITLE
Don't record some popup windows as primary history

### ISSUE THREAD

**Issue by darkwing** [mozilla/tofino#743]
I visited a page and clicked the "Share on Twitter" link.  Normally a tiny popup would launch but Tofino opens it in a new tab -- no big deal.  When I view the history list, however, the URL and page show up.

Is there a way we can identify URLs which we don't want to display as history?  Maybe URLs in named, sized windows?  Just a thought; feel free to simply close.

**Comment by jsantell** [comment]
This should probably be handled on the UA service, filtering out (via configuration?) pages opened via popup style.

**Comment by rnewman** [comment]
See also #663.

**Comment by jsantell** [comment]
This is now a dupe of #663
