### ISSUE TITLE
Implement tab overview with page summaries

### ISSUE THREAD

**Issue by phlsa** [mozilla/tofino#747]
Since a tab overview with page summaries did very well in user testing and also provides us with a basis for further development, we'd like to test it in a live product.

A (clickable) wireframe can be found here:
https://invis.io/2R7DXRM5E#/158003931_Overview

Here's a rough description of the feature:
- The user gets an overview button on the leftmost side of the tab strip
- Clicking that button reveals a full-window overview of all open tabs. Each tab is represented as a card
- Clicking anywhere on the card brings the user to the tab
- (not critical now, but we'll want that at some point: tab cards should be rearrangeable)

The wireframe shows a very ideal case where a lot of data is being scraped from the websites. To be a bit more pragmatic, here's what we should definitely have in the card:
- Key image
- Key color
- Favicon (or better, touch icon)
- Title (this doesn't need to be the `<title>` tag from the website. For example, Amazon prepends »Amazon.com« to the actual title. In that case, we should strip the »Amazon.com« out)
- Excerpt of body text (for articles in particular)
- Star rating (for anything where star ratings exist). We can be pragmatic here and only implement that for Amazon for now

I will follow up here with a higher fidelity mockup of the screen and the various kinds of cards.

One thing that »different kinds of cards for different kinds of websites« implies is that we have some rough categorization of websites (e.g. being able to tell a product page from an article from a recipe). @rnewman do you happen to know if that's something we can do yet?

**Comment by rnewman** [comment]
Existing Mozilla tools can currently do:

* OG type — e.g., article, website. This is unlikely to be sufficient categorization for you.
* Title, URL, description.
* Image and icon(s).

We can special-case title and star rating extraction for Amazon using rules for Fathom.

The page summary folks are aware of, and are working towards, the full range of things you mention.

Categorization by domain or URL match is a tractible problem.

Categorization by available data — e.g., price + star rating + image = rich product card; price + star rating = slim product card — was the topic of my PhD, and reasonable heuristics exist.

**Comment by phlsa** [comment]
Is there a list of metadata we can easily grab (through FB metadata, Twitter cards etc.)? I'm currently designing summary layouts for a bunch of page types and it would be very helpful to know what is out there.

**Comment by phlsa** [comment]
This is what I have so far. The browser layout should be pretty stable. The layout of the summaries themselves less so (see last comment)

![page](https://cloud.githubusercontent.com/assets/514315/16498113/82b31796-3efa-11e6-8bba-f112192c28b2.png)


![tab overview](https://cloud.githubusercontent.com/assets/514315/16498119/87d33882-3efa-11e6-99c6-e5ccc6c127c6.png)


![summaries](https://cloud.githubusercontent.com/assets/514315/16498121/8a94969c-3efa-11e6-8c30-fc2604b4ac8b.png)

**Comment by victorporof** [comment]
Nice!

**Comment by victorporof** [comment]
@phlsa Can I get a svg asset for the "Overview" button icon?

**Comment by phlsa** [comment]
There you go!

[OverviewIcon.zip](https://github.com/mozilla/tofino/files/364006/OverviewIcon.zip)

**Comment by victorporof** [comment]
Nice!

**Comment by victorporof** [comment]
@phlsa Since we're at it, mind sending me updated assets for the back, forward, reload, star and maybe also the window control buttons? The current svgs are rather different from the mockup above.

**Comment by phlsa** [comment]
I don't think we need to update the icons at this moment since the changes would be only stylistically. TBH, the only reason for the icons to be different at all is that I didn't have the original assets, so I quickly created my own for the mockup. From the screen shots you posted, the icons look fitting enough for testing :)

**Comment by victorporof** [comment]
This is done.
