### ISSUE TITLE
Add full text indexing to DataScript backed storage

### ISSUE THREAD

**Issue by ncalexan** [mozilla/tofino#751]
The Datomic API is built in two parts.  First, one adds `:db/fulltext true` to the attribute schema.  Second, one queries with `(fulltext ...)`.  See http://docs.datomic.com/schema.html and http://docs.datomic.com/query.html#fulltext.

Supporting this in DataScript is rather awkward, since the DS `q` and `transact!` API are both synchronous.  In #746, I am working around the latter by making `transact` async and manually invoking our asynchronous listener to do IO against the SQLite store.  We can certainly do the same for `q`, and essentially await for a `(fulltext ...)` query before interpolating the result into DS's sync `q` API.  It's dissatisfying.

**Comment by ncalexan** [comment]
@rnewman, your thoughts?

**Comment by rnewman** [comment]
Smells a lot like GraphQL, doesn't it?

Concerns:

`transact` subparts are tricksy. You need to get an ID from one store, put it into another, and ensure that the entire transaction commits together, or rolls back together in the case of failure. Consider the case where there are two `fulltext` attributes being added in a single `transact` call, and one fails to be written to the DB. This isn't quite a distributed transaction problem, but it involves management of transactions — you need to open a DB transaction at first DB write, and commit it when you have advanced to a new DS state.

Java and Clojure's concurrency models are fundamentally synchronous-within-thread. Node's is callback-single-threaded. JS barely has one. DS doesn't have a pressing need to do asynchrony, being in-memory and often used in Clojure. I'm not entirely convinced by Node's model, particularly the use of callbacks or promises; splashing `async` around is something of an all-or-nothing option. Observable gets us a lot closer — you can return and process results as they arrive — but it still bleeds all the way up the stack. This stack is fundamentally not built to do this well, which indeed leads to dissatisfaction.

It's possible to avoid async `q` by doing `fulltext` access separately/first/programmatically, but that's a bit of a hack. I don't see a good way to avoid async `q` if sqlite is involved.

**Comment by ncalexan** [comment]
I'm not sure I see why this is GraphQL-ish, because it's not clear to me that GraphQL is concerned with writes.  I suppose GraphQL does consider read-joins across stores, but in this case the painful part is that the single live version of an SQLite fulltext index plays poorly with the multi-version DS store.  There's no GraphQL equivalent to multi-version stores.

Our out for `transact` tricksiness is... to be tricksy.  We've already got an async internal `transact`; we can leverage that to do the fulltext index insertions.  I agree this is hard and error prone but I think we can do it.

As for the fundamentally different concurrency models, I concur: rock and hard places.  For the record DS, grew from ClojureScript and I believe most consumers are on the JS VM, not the JVM.  We're a strange consumer since we're in Node.js and interacting with async systems in a way that most JS consumers will not.

I'm starting to feel that DS is not helping us enough.  We can fork DS to handle async function calls, but I feel like we're going to end up at the end of a dark tunnel.

Backing up, the multi-version, DB-as-value model of Datomic provides value when reads are distributed to peers.  For us, those peers would be the BrowserWindow instances.  But that's not our case: we are arguing for a single service for reads and writes.  I think we should embrace that and consider more seriously backing everything against SQLite, thereby baking our text indexing in at a low level.

**Comment by rnewman** [comment]
Yeah, [GraphQL does mutations](https://facebook.github.io/relay/docs/graphql-mutations.html). The main similarity in my mind is that we have a tree-shaped expression where different parts of it are written into/read from different stores or APIs. That's exactly what GraphQL aims to address, and the similarity is interesting.

I don't think I have as monolithic a perspective on the value of Datomic's modeling. Yes, it makes replication out to query peers tractible. It also makes layering of derived/learned/cached storage — something I think we'll do — a little easier. It makes syncing/backup/auditing easier. It makes currently complicated concepts like clearing recent history into very straightforward operations.

I'm not opposed to implementing a similar library, or a DS storage layer, directly on top of sqlite, rather than trying to implement raw persistence for DataScript; quite the opposite. But I do think care needs to be taken when reimplementing the wheel, particularly if doing so involves reinventing some concepts.

**Comment by ncalexan** [comment]
> Yeah, GraphQL does mutations. The main similarity in my mind is that we have a tree-shaped expression where different parts of it are written into/read from different stores or APIs. That's exactly what GraphQL aims to address, and the similarity is interesting.

Based on what you link to, GQL doesn't say anything about transactions or atomicity.  So yes, GQL provides the framework; but the nuts and bolts are still implementation specific.  We can do those in a general framework or not.

> I'm not opposed to implementing a similar library, or a DS storage layer, directly on top of sqlite, rather than trying to implement raw persistence for DataScript; quite the opposite. But I do think care needs to be taken when reimplementing the wheel, particularly if doing so involves reinventing some concepts.

OK.

> It's possible to avoid async q by doing fulltext access separately/first/programmatically, but that's a bit of a hack. I don't see a good way to avoid async q if sqlite is involved.

I've dug into DataScript's `q` implementation, and I think it will be very difficult to make a channel-aware `q!`.  There are just a ton of layers in the existing code so it's very hard to adapt a small part to use channels.  I think our best option will be to preprocess incoming queries, perhaps only handling the situation where the very first `:where` clause is `(fulltext ...)`, or perhaps adding our own `:fulltext` clause that translates into a canned initial `:where [(fulltext ...)]` clause.

**Comment by rnewman** [comment]
-> Datomish.
