### ISSUE TITLE
fetch-mock spam

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#785]
This gets dumped out when running tests. Should set `greed` to whatever makes sense.

```
/* * * * * * * * * * * * * * * * * * * * * * * */
Pro tip for fetch-mock:
By default any unmatched calls go straight through to `fetch`. Set `fetchMock.greed = 'bad'` to make them all error, or `fetchMock.greed = 'good'` to return `200` responses
/* * * * * * * * * * * * * * * * * * * * * * * */
```

**Comment by Mossop** [comment]
It's worse than that. It seems to be outputting a random "tip" on every test run.

**Comment by Mossop** [comment]
Looks like this was caused by https://github.com/wheresrhys/fetch-mock/pull/107

**Comment by Mossop** [comment]
@jsantell Want to just downgrade us to 4.5.4, looks like the only difference between that and the current release is the tips.

**Comment by pdehaan** [comment]
FWIW (not much), I filed a PR to disable the protips in CI environments; https://github.com/wheresrhys/fetch-mock/pull/109

**Comment by victorporof** [comment]
This seems to be gone now, closing.
