### ISSUE TITLE
CI is using node 6.1

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#789]
Examples:

https://ci.appveyor.com/project/Mozilla/tofino-u1hv8/build/1.0.681-rripapcw/job/2rq19b3b9t1929rm
https://travis-ci.org/mozilla/tofino/jobs/142946820

@Mossop any opinions on if we should update?  6.3 is out now: https://nodejs.org/en/blog/release/v6.3.0/.   Our documentation says >= 6.1 (https://github.com/mozilla/tofino/blob/master/docs/building.md#all-platforms) but might be good to stay up to date in our packaged builds.

**Comment by Mossop** [comment]
I'd prefer to keep us fixed to whatever version of node ships in Electron itself. This makes sure that our standalone tests run in the same node that they will run when in the app. Right now that is 6.1.0

**Comment by bgrins** [comment]
Alright, makes sense
