### ISSUE TITLE
The "Directory-Layout" wiki page is horribly out of date

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#79]
https://github.com/mozilla/tofino/wiki/Directory-Layout

**Comment by jsantell** [comment]
So is the in-tree README that was explaining the same/similar thing https://github.com/mozilla/tofino/blob/master/app/README.md

**Comment by victorporof** [comment]
👍

**Comment by Mossop** [comment]
I've linked there from the wiki.
