### ISSUE TITLE
ENOENT: no such file or directory, open '/tofino/.electron/version'

### ISSUE THREAD

**Issue by iDev0urer** [mozilla/tofino#790]
For some reason when trying to build from scratch, electron doesn't seem to be installing correctly.

I have tried deleting the node_modules directory, running the clobber command, and re running npm install all with no luck

Node version: 6.2.2
Python version: 2.7.1
OS: Debian 8

**Comment by Mossop** [comment]
Can you show us a log of running npm install from scratch?

**Comment by Mossop** [comment]
I'm closing this since without more information we can't work on this issue.
