### ISSUE TITLE
Suggestion: Re-create advanced UI customizations similar before Australis (optionally/hidden)

### ISSUE THREAD

**Issue by CountLesnik** [mozilla/tofino#803]
A major reason why Mozilla has decided to remove customization was also for sure that the browser gets more responsible and faster and Gecko had not the benefit to count speed as it's main strength like for example Blink has, but if having a system like Electron or the Servo engine plans available where the engine is incredible fast, why not implementing again UI customization features when the engine speed allows to do so?

Also, old UI customization or complex theme options has been a reason why many advanced users have picked Firefox in the beginning, which are now leaving as the feature set they have grown comfortable with is outsourced one after another.

Another aspect to consider doing so is that simplicity and minimalism and features do not exclude one another. And browsers like Vivaldi, Brave or the new Opera show that there is still much interest in having a more complex built inside feature set, may it be customization or privacy protecting features like built inside adblock or No-Script like functionality.

Would be nice if that would be considered as Tofino is a project where other concepts can be explored, which for sure does not exclude a more rich feature set (which seems to be something mainline Firefox is trying to avoid as long as the engine is not able to support both speed and complexity at the same time)

Thanks!

**Comment by Mossop** [comment]
As an experimentation platform I think it is very unlikely we'd want to build and maintain significant customization ability, we likely don't even want users to be able to change the branch of the UI that they will be using.

**Comment by Mossop** [comment]
Confirmed with product team, we're not interested in working on this right now.
