### ISSUE TITLE
Allow the app to run immediately after launching the osx disk image

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#814]
If you download a packaged OSX build that opens a folder showing both the app and the Applications directory ([example](https://github.com/mozilla/tofino/releases/download/v0.1.0/tofino-darwin-x64.dmg)), double clicking the app results in the process starting up, but no browser windows open.

I believe this is because the folder / dmg it's trying to write to for the profile database / logs isn't writeable.  A couple of options:

1) We could write to a temp directory just in this case.  That's easy, but your profile data would get lost when you drag / drop the app into the Applications directory.
2) We could switch to using a shared appdata folder across all tofinos regardless of if the app directory is writeable. Maybe this is what we want to ultimately get to, but I have a couple of concerns with it now.  First, it could potentially mess up usertesting.com builds if the same user is doing two different tests and the latter is polluted with the profile data from the former.  Second, now we get to do profile migrations across versions.

**Comment by bgrins** [comment]
Depends on #809

**Comment by Mossop** [comment]
#564 is open to define a real profile directory

**Comment by bgrins** [comment]
OK maybe this should be closed in favor of that, then.  Not sure if there's a big benefit to having a temporary fix in place

**Comment by Mossop** [comment]
Worth keeping this open to check that that does actually fix it, there might be other issues.
