### ISSUE TITLE
Text hard to read on OSX

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#836]
<img width="643" alt="screen shot 2016-07-19 at 12 32 11 pm" src="https://cloud.githubusercontent.com/assets/641267/16963826/31238a70-4dad-11e6-8a66-7c7999a43e95.png">

The font changes recently (especially in the input element) is very hard to read due to font weight from the thin lines in the blueprint background. @victorporof @phlsa would removing the background image or thickening the font be acceptable?

**Comment by victorporof** [comment]
I did that intentionally to follow the mockups. I can increase weight if desired.

**Comment by phlsa** [comment]
Sorry, that must have come from the font rendering when exporting images.
We never really talked about fonts though, so let's do it now :)

My suggestion would be to do the following:
- Windows: Segoe UI Regular
- macOS: San Francisco Text Regular (or Helvetica Regular on older systems)
- Linux: Ubuntu Sans Regular

The browser will look slightly different on the respective platforms that way, but I'd argue that this is a good thing.

**Comment by paanvaannd** [comment]
Came here with the same issue! I would really appreciate removing the grid background from the macOS version. It makes things hard to read across the UI:

![screenshot 2016-08-14 22 55 56](https://cloud.githubusercontent.com/assets/16567134/17654557/53df80e4-6272-11e6-8f36-39bd2659002b.png)

Also, I agree that making the browser looking slightly different across platforms would be a good thing. It adds a bit of nativity to the browser within each OS.
