### ISSUE TITLE
Failed prop type: Required prop `src` was not specified in `Thumbnail`

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#861]
After merging in #856, this started occuring. Looks like both Thumbnail and BaseCard are both using the backgroundImage. I'm not sure what's intended here, which should be removed?

warning.js:44Warning: Failed prop type: Required prop `src` was not specified in `Thumbnail`

**Comment by victorporof** [comment]
None should be removed, just need to supply them in tests so react doesn't complain.

**Comment by victorporof** [comment]
Now I see this happens at runtime! Fixed in Fixed by https://github.com/mozilla/tofino/commit/d84df787b1bbaac67c6667c62f2d33203f2b9679
