### ISSUE TITLE
Packaging /app to asar file (when `npm run package`?)

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/tofino#87]
https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md

That have 17000+ files in /dist/tofino-win32-x64/resources/app, it is a horrible effects for end users, although we may have no plans.

In command line way: `asar p app app.asar`
Then, renamed or removed the `app` dir.

**Comment by Mossop** [comment]
This depends on #564

**Comment by Mossop** [comment]
Fixed by #838
