### ISSUE TITLE
Do not reset URL bar value when load finishes if user has typed something else in the mean time

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#888]
STR:
Open a new tab with ctrl+T (which begins loading `tofino://history`)
Quickly type something in URL bar
Let page finish loading

Expected:
URL bar value is the thing you typed.  (if you press escape then it should reset to "tofino://history").

Actual:
URL bar value is set to "tofino://history"

**Comment by victorporof** [comment]
I believe this is fixed in the new frontend. Please reopen if not.
