### ISSUE TITLE
Social lock button

### ISSUE THREAD

**Issue by vsethuooo** [mozilla/tofino#934]
I understand that Tofino is an exprimental web browser. So, I hope this is a good place for discussing more here. So, how many times have you guys ended up being on facebook.com, without even realizing that you're on it. I'm sure each of us have faced this problem about a million times, when I'm trying to concentrate on my work, and out of nowhere I'm scrolling my FB news feed. Also, the fact that the modern day browsers making it so easy to get on any website, all I need to do is press the 'F' key, and the rest is magic, I'm on it, before I know it.

So, I'm thinking of a social lock button, (maybe somewhere on the bottom right corner), is not a bad idea after all. A browser built-in feature for self-control to prevent accidental use of facebook, twitter and other social websites, which you want to purposely avoid, while you are doing something productive.

So when you get to work, begin by clicking on the social lock button. So, even when you enter FB without realizing, the browser will redirect you to a different page. And when you really need to enter social media, unlock yourself by clicking the button again, and voila you're free to access whatever you want. The trick is it needs a little bit of conscience to lock/unlock yourself if such a feature in place. So,  I'm sure you won't accidentally unlock yourself when you're trying to work.

Also, the toggle lock has to be visible in the open browser. If it is somewhere in the menu, the chances are that, people won't go out of their way to lock themselves out of social media.

Thanks for taking your time to read what I had to say people. Please let me know your thoughts on this. Please comment a '+1' if you think this will be useful.

**Comment by victorporof** [comment]
Not looking into working on this at the moment.
