### ISSUE TITLE
[Suggested Feature] Tab groups

### ISSUE THREAD

**Issue by paanvaannd** [mozilla/tofino#958]
Grouping tabs, as in Vivaldi or before Firefox 45, was a great way of organizing tabs for those with a lot of tabs. Integrating tab grouping with Overview offers better tab management for users. The option to automatically group tabs based on parent site (say, through a right-click option) would also be a welcome addition.

Related issue: #954, #955, #956, #957

**Comment by joewalker** [comment]
Thanks for this suggestion. Our telemetry for tab groups in Firefox showed that it was used (and loved) by many users (including me) but the majority of people didn't get it. And it encouraged people to forget about tabs and end up with a huge working set.

We're thinking about a way to archive tabs and create tab collections in Tofino, and hope that will answer the tab-management problem, but I don't think this will end up looking like Tab Groups from old Firefox. So I'm going to close this bug.

When we have some mock-ups to share I'll try to remember to make them public somewhere.
