### ISSUE TITLE
Less chrome after scrolling

### ISSUE THREAD

**Issue by paanvaannd** [mozilla/tofino#960]
*Another* front end suggestion :+)

Taking a page out of mobile browsers, I think it would be nice for the nonessential chrome to move out of the way after a user scrolls on the site.

For example, scrolling on a results page of a search query would cause the navigation bar to slide up and be hidden. Perhaps scrolling up again makes the navigation bar chrome visible again, as it does in mobile browsers on iOS, but I would suggest only showing it on hovering over the tab bar again to toggle visibility of the navigation bar chrome.

i) More space for web content

ii) "Smart" browsers are, in my opinion, context-specific: only showing what is necessary at any time unless told by the user to show something extra

iii) Hovering over the tab bar should result in a manual toggle rather than a timed toggle, since the navigation bar disappearing again automatically when no action is taken would, in my opinion, be more annoying than helpful in this case
- i.e. the navigation chrome would not simply disappear again after a couple seconds, even if the cursor is removed from the tab bar; only hide the navigation bar again after the user hovers over the tab bar once more or upon scrolling on the web page again

**Comment by victorporof** [comment]
We had something this a while ago, but removed it in favor of having simpler code for prototyping: https://twitter.com/jsantell/status/723265275911540737 We'll likely add it back soon.

**Comment by rnewman** [comment]
Thanks for the suggestion!

This was too difficult to implement and was less useful on desktop than on mobile. WONTFIXing for now.

**Comment by paanvaannd** [comment]
Thank you for considering the suggestion!

I hope I can at least try this out some day in the near future, but I can see how it might be less useful for desktop browsing than on mobile.

Have a great week!
