### ISSUE TITLE
No download notification

### ISSUE THREAD

**Issue by jsantell** [mozilla/tofino#998]
On OSX, a file pops up in the downloads dock immediately, and in Firefox, I can see its progression in the toolbar so I know if and when it is done. Without this notification, I'm attempting to open the incomplete file from my Downloads in the dock.

**Comment by jsantell** [comment]
With the frontend changes it's now not possible to even download something (no cmd+S, no right click menu, no app menu with save), so that's probably first thing to do.

**Comment by victorporof** [comment]
See https://github.com/mozilla/tofino/issues/1070#issuecomment-246093441
